// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module L1CohMetaArray(
  input        clock,
  input        reset,
  input        io_read_0_valid,
  input        io_read_0_bits_idx,
  input        io_read_1_valid,
  input        io_read_1_bits_idx,
  input        io_read_2_valid,
  input        io_read_2_bits_idx,
  input        io_read_3_valid,
  input        io_read_3_bits_idx,
  output [1:0] io_resp_0_0_coh_state,
  output [1:0] io_resp_0_1_coh_state,
  output [1:0] io_resp_0_2_coh_state,
  output [1:0] io_resp_0_3_coh_state,
  output [1:0] io_resp_1_0_coh_state,
  output [1:0] io_resp_1_1_coh_state,
  output [1:0] io_resp_1_2_coh_state,
  output [1:0] io_resp_1_3_coh_state,
  output [1:0] io_resp_2_0_coh_state,
  output [1:0] io_resp_2_1_coh_state,
  output [1:0] io_resp_2_2_coh_state,
  output [1:0] io_resp_2_3_coh_state,
  output [1:0] io_resp_3_0_coh_state,
  output [1:0] io_resp_3_1_coh_state,
  output [1:0] io_resp_3_2_coh_state,
  output [1:0] io_resp_3_3_coh_state,
  input        io_write_0_valid,
  input        io_write_0_bits_idx,
  input  [3:0] io_write_0_bits_way_en,
  input  [1:0] io_write_0_bits_meta_coh_state
);

  reg  [1:0] meta_array_0_0_coh_state;
  reg  [1:0] meta_array_0_1_coh_state;
  reg  [1:0] meta_array_0_2_coh_state;
  reg  [1:0] meta_array_0_3_coh_state;
  reg  [1:0] meta_array_1_0_coh_state;
  reg  [1:0] meta_array_1_1_coh_state;
  reg  [1:0] meta_array_1_2_coh_state;
  reg  [1:0] meta_array_1_3_coh_state;
  reg        io_resp_0_0_r;
  reg        io_resp_0_1_r;
  reg        io_resp_0_2_r;
  reg        io_resp_0_3_r;
  reg        io_resp_1_0_r;
  reg        io_resp_1_1_r;
  reg        io_resp_1_2_r;
  reg        io_resp_1_3_r;
  reg        io_resp_2_0_r;
  reg        io_resp_2_1_r;
  reg        io_resp_2_2_r;
  reg        io_resp_2_3_r;
  reg        io_resp_3_0_r;
  reg        io_resp_3_1_r;
  reg        io_resp_3_2_r;
  reg        io_resp_3_3_r;
  reg        s1_way_wen_0_0_REG;
  reg        s1_way_waddr_0_0_r;
  reg  [1:0] s1_way_wdata_0_0_r_coh_state;
  reg        s1_way_wen_1_0_REG;
  reg        s1_way_waddr_1_0_r;
  reg  [1:0] s1_way_wdata_1_0_r_coh_state;
  reg        s1_way_wen_2_0_REG;
  reg        s1_way_waddr_2_0_r;
  reg  [1:0] s1_way_wdata_2_0_r_coh_state;
  reg        s1_way_wen_3_0_REG;
  reg        s1_way_waddr_3_0_r;
  reg  [1:0] s1_way_wdata_3_0_r_coh_state;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      meta_array_0_0_coh_state <= 2'h0;
      meta_array_0_1_coh_state <= 2'h0;
      meta_array_0_2_coh_state <= 2'h0;
      meta_array_0_3_coh_state <= 2'h0;
      meta_array_1_0_coh_state <= 2'h0;
      meta_array_1_1_coh_state <= 2'h0;
      meta_array_1_2_coh_state <= 2'h0;
      meta_array_1_3_coh_state <= 2'h0;
    end
    else begin
      if (s1_way_wen_0_0_REG & ~s1_way_waddr_0_0_r)
        meta_array_0_0_coh_state <= s1_way_wdata_0_0_r_coh_state;
      if (s1_way_wen_1_0_REG & ~s1_way_waddr_1_0_r)
        meta_array_0_1_coh_state <= s1_way_wdata_1_0_r_coh_state;
      if (s1_way_wen_2_0_REG & ~s1_way_waddr_2_0_r)
        meta_array_0_2_coh_state <= s1_way_wdata_2_0_r_coh_state;
      if (s1_way_wen_3_0_REG & ~s1_way_waddr_3_0_r)
        meta_array_0_3_coh_state <= s1_way_wdata_3_0_r_coh_state;
      if (s1_way_wen_0_0_REG & s1_way_waddr_0_0_r)
        meta_array_1_0_coh_state <= s1_way_wdata_0_0_r_coh_state;
      if (s1_way_wen_1_0_REG & s1_way_waddr_1_0_r)
        meta_array_1_1_coh_state <= s1_way_wdata_1_0_r_coh_state;
      if (s1_way_wen_2_0_REG & s1_way_waddr_2_0_r)
        meta_array_1_2_coh_state <= s1_way_wdata_2_0_r_coh_state;
      if (s1_way_wen_3_0_REG & s1_way_waddr_3_0_r)
        meta_array_1_3_coh_state <= s1_way_wdata_3_0_r_coh_state;
    end
  end // always @(posedge, posedge)
  wire       s0_way_wen_0_0 = io_write_0_valid & io_write_0_bits_way_en[0];
  wire       s0_way_wen_1_0 = io_write_0_valid & io_write_0_bits_way_en[1];
  wire       s0_way_wen_2_0 = io_write_0_valid & io_write_0_bits_way_en[2];
  wire       s0_way_wen_3_0 = io_write_0_valid & io_write_0_bits_way_en[3];
  always @(posedge clock) begin
    if (io_read_0_valid) begin
      io_resp_0_0_r <= io_read_0_bits_idx;
      io_resp_0_1_r <= io_read_0_bits_idx;
      io_resp_0_2_r <= io_read_0_bits_idx;
      io_resp_0_3_r <= io_read_0_bits_idx;
    end
    if (io_read_1_valid) begin
      io_resp_1_0_r <= io_read_1_bits_idx;
      io_resp_1_1_r <= io_read_1_bits_idx;
      io_resp_1_2_r <= io_read_1_bits_idx;
      io_resp_1_3_r <= io_read_1_bits_idx;
    end
    if (io_read_2_valid) begin
      io_resp_2_0_r <= io_read_2_bits_idx;
      io_resp_2_1_r <= io_read_2_bits_idx;
      io_resp_2_2_r <= io_read_2_bits_idx;
      io_resp_2_3_r <= io_read_2_bits_idx;
    end
    if (io_read_3_valid) begin
      io_resp_3_0_r <= io_read_3_bits_idx;
      io_resp_3_1_r <= io_read_3_bits_idx;
      io_resp_3_2_r <= io_read_3_bits_idx;
      io_resp_3_3_r <= io_read_3_bits_idx;
    end
    s1_way_wen_0_0_REG <= s0_way_wen_0_0;
    if (s0_way_wen_0_0) begin
      s1_way_waddr_0_0_r <= io_write_0_bits_idx;
      s1_way_wdata_0_0_r_coh_state <= io_write_0_bits_meta_coh_state;
    end
    s1_way_wen_1_0_REG <= s0_way_wen_1_0;
    if (s0_way_wen_1_0) begin
      s1_way_waddr_1_0_r <= io_write_0_bits_idx;
      s1_way_wdata_1_0_r_coh_state <= io_write_0_bits_meta_coh_state;
    end
    s1_way_wen_2_0_REG <= s0_way_wen_2_0;
    if (s0_way_wen_2_0) begin
      s1_way_waddr_2_0_r <= io_write_0_bits_idx;
      s1_way_wdata_2_0_r_coh_state <= io_write_0_bits_meta_coh_state;
    end
    s1_way_wen_3_0_REG <= s0_way_wen_3_0;
    if (s0_way_wen_3_0) begin
      s1_way_waddr_3_0_r <= io_write_0_bits_idx;
      s1_way_wdata_3_0_r_coh_state <= io_write_0_bits_meta_coh_state;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;
        end
        meta_array_0_0_coh_state = _RANDOM[1'h0][1:0];
        meta_array_0_1_coh_state = _RANDOM[1'h0][3:2];
        meta_array_0_2_coh_state = _RANDOM[1'h0][5:4];
        meta_array_0_3_coh_state = _RANDOM[1'h0][7:6];
        meta_array_1_0_coh_state = _RANDOM[1'h0][9:8];
        meta_array_1_1_coh_state = _RANDOM[1'h0][11:10];
        meta_array_1_2_coh_state = _RANDOM[1'h0][13:12];
        meta_array_1_3_coh_state = _RANDOM[1'h0][15:14];
        io_resp_0_0_r = _RANDOM[1'h0][16];
        io_resp_0_1_r = _RANDOM[1'h0][17];
        io_resp_0_2_r = _RANDOM[1'h0][18];
        io_resp_0_3_r = _RANDOM[1'h0][19];
        io_resp_1_0_r = _RANDOM[1'h0][20];
        io_resp_1_1_r = _RANDOM[1'h0][21];
        io_resp_1_2_r = _RANDOM[1'h0][22];
        io_resp_1_3_r = _RANDOM[1'h0][23];
        io_resp_2_0_r = _RANDOM[1'h0][24];
        io_resp_2_1_r = _RANDOM[1'h0][25];
        io_resp_2_2_r = _RANDOM[1'h0][26];
        io_resp_2_3_r = _RANDOM[1'h0][27];
        io_resp_3_0_r = _RANDOM[1'h0][28];
        io_resp_3_1_r = _RANDOM[1'h0][29];
        io_resp_3_2_r = _RANDOM[1'h0][30];
        io_resp_3_3_r = _RANDOM[1'h0][31];
        s1_way_wen_0_0_REG = _RANDOM[1'h1][0];
        s1_way_waddr_0_0_r = _RANDOM[1'h1][1];
        s1_way_wdata_0_0_r_coh_state = _RANDOM[1'h1][3:2];
        s1_way_wen_1_0_REG = _RANDOM[1'h1][4];
        s1_way_waddr_1_0_r = _RANDOM[1'h1][5];
        s1_way_wdata_1_0_r_coh_state = _RANDOM[1'h1][7:6];
        s1_way_wen_2_0_REG = _RANDOM[1'h1][8];
        s1_way_waddr_2_0_r = _RANDOM[1'h1][9];
        s1_way_wdata_2_0_r_coh_state = _RANDOM[1'h1][11:10];
        s1_way_wen_3_0_REG = _RANDOM[1'h1][12];
        s1_way_waddr_3_0_r = _RANDOM[1'h1][13];
        s1_way_wdata_3_0_r_coh_state = _RANDOM[1'h1][15:14];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        meta_array_0_0_coh_state = 2'h0;
        meta_array_0_1_coh_state = 2'h0;
        meta_array_0_2_coh_state = 2'h0;
        meta_array_0_3_coh_state = 2'h0;
        meta_array_1_0_coh_state = 2'h0;
        meta_array_1_1_coh_state = 2'h0;
        meta_array_1_2_coh_state = 2'h0;
        meta_array_1_3_coh_state = 2'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_resp_0_0_coh_state =
    io_resp_0_0_r ? meta_array_1_0_coh_state : meta_array_0_0_coh_state;
  assign io_resp_0_1_coh_state =
    io_resp_0_1_r ? meta_array_1_1_coh_state : meta_array_0_1_coh_state;
  assign io_resp_0_2_coh_state =
    io_resp_0_2_r ? meta_array_1_2_coh_state : meta_array_0_2_coh_state;
  assign io_resp_0_3_coh_state =
    io_resp_0_3_r ? meta_array_1_3_coh_state : meta_array_0_3_coh_state;
  assign io_resp_1_0_coh_state =
    io_resp_1_0_r ? meta_array_1_0_coh_state : meta_array_0_0_coh_state;
  assign io_resp_1_1_coh_state =
    io_resp_1_1_r ? meta_array_1_1_coh_state : meta_array_0_1_coh_state;
  assign io_resp_1_2_coh_state =
    io_resp_1_2_r ? meta_array_1_2_coh_state : meta_array_0_2_coh_state;
  assign io_resp_1_3_coh_state =
    io_resp_1_3_r ? meta_array_1_3_coh_state : meta_array_0_3_coh_state;
  assign io_resp_2_0_coh_state =
    io_resp_2_0_r ? meta_array_1_0_coh_state : meta_array_0_0_coh_state;
  assign io_resp_2_1_coh_state =
    io_resp_2_1_r ? meta_array_1_1_coh_state : meta_array_0_1_coh_state;
  assign io_resp_2_2_coh_state =
    io_resp_2_2_r ? meta_array_1_2_coh_state : meta_array_0_2_coh_state;
  assign io_resp_2_3_coh_state =
    io_resp_2_3_r ? meta_array_1_3_coh_state : meta_array_0_3_coh_state;
  assign io_resp_3_0_coh_state =
    io_resp_3_0_r ? meta_array_1_0_coh_state : meta_array_0_0_coh_state;
  assign io_resp_3_1_coh_state =
    io_resp_3_1_r ? meta_array_1_1_coh_state : meta_array_0_1_coh_state;
  assign io_resp_3_2_coh_state =
    io_resp_3_2_r ? meta_array_1_2_coh_state : meta_array_0_2_coh_state;
  assign io_resp_3_3_coh_state =
    io_resp_3_3_r ? meta_array_1_3_coh_state : meta_array_0_3_coh_state;
endmodule

