// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module PMAEntryHandleModule(
  input         clock,
  input         reset,
  input         io_in_wen,
  input         io_in_ren,
  input  [11:0] io_in_addr,
  input  [63:0] io_in_wdata,
  input         io_in_pmaCfg_0_R,
  input         io_in_pmaCfg_0_W,
  input         io_in_pmaCfg_0_X,
  input  [1:0]  io_in_pmaCfg_0_A,
  input         io_in_pmaCfg_0_L,
  input         io_in_pmaCfg_0_ATOMIC,
  input         io_in_pmaCfg_0_C,
  input         io_in_pmaCfg_1_R,
  input         io_in_pmaCfg_1_W,
  input         io_in_pmaCfg_1_X,
  input  [1:0]  io_in_pmaCfg_1_A,
  input         io_in_pmaCfg_1_L,
  input         io_in_pmaCfg_1_ATOMIC,
  input         io_in_pmaCfg_1_C,
  input         io_in_pmaCfg_2_R,
  input         io_in_pmaCfg_2_W,
  input         io_in_pmaCfg_2_X,
  input  [1:0]  io_in_pmaCfg_2_A,
  input         io_in_pmaCfg_2_L,
  input         io_in_pmaCfg_2_ATOMIC,
  input         io_in_pmaCfg_2_C,
  input         io_in_pmaCfg_3_R,
  input         io_in_pmaCfg_3_W,
  input         io_in_pmaCfg_3_X,
  input  [1:0]  io_in_pmaCfg_3_A,
  input         io_in_pmaCfg_3_L,
  input         io_in_pmaCfg_3_ATOMIC,
  input         io_in_pmaCfg_3_C,
  input         io_in_pmaCfg_4_R,
  input         io_in_pmaCfg_4_W,
  input         io_in_pmaCfg_4_X,
  input  [1:0]  io_in_pmaCfg_4_A,
  input         io_in_pmaCfg_4_L,
  input         io_in_pmaCfg_4_ATOMIC,
  input         io_in_pmaCfg_4_C,
  input         io_in_pmaCfg_5_R,
  input         io_in_pmaCfg_5_W,
  input         io_in_pmaCfg_5_X,
  input  [1:0]  io_in_pmaCfg_5_A,
  input         io_in_pmaCfg_5_L,
  input         io_in_pmaCfg_5_ATOMIC,
  input         io_in_pmaCfg_5_C,
  input         io_in_pmaCfg_6_R,
  input         io_in_pmaCfg_6_W,
  input         io_in_pmaCfg_6_X,
  input  [1:0]  io_in_pmaCfg_6_A,
  input         io_in_pmaCfg_6_L,
  input         io_in_pmaCfg_6_ATOMIC,
  input         io_in_pmaCfg_6_C,
  input         io_in_pmaCfg_7_R,
  input         io_in_pmaCfg_7_W,
  input         io_in_pmaCfg_7_X,
  input  [1:0]  io_in_pmaCfg_7_A,
  input         io_in_pmaCfg_7_L,
  input         io_in_pmaCfg_7_ATOMIC,
  input         io_in_pmaCfg_7_C,
  input         io_in_pmaCfg_8_R,
  input         io_in_pmaCfg_8_W,
  input         io_in_pmaCfg_8_X,
  input  [1:0]  io_in_pmaCfg_8_A,
  input         io_in_pmaCfg_8_L,
  input         io_in_pmaCfg_8_ATOMIC,
  input         io_in_pmaCfg_8_C,
  input         io_in_pmaCfg_9_R,
  input         io_in_pmaCfg_9_W,
  input         io_in_pmaCfg_9_X,
  input  [1:0]  io_in_pmaCfg_9_A,
  input         io_in_pmaCfg_9_L,
  input         io_in_pmaCfg_9_ATOMIC,
  input         io_in_pmaCfg_9_C,
  input         io_in_pmaCfg_10_R,
  input         io_in_pmaCfg_10_W,
  input         io_in_pmaCfg_10_X,
  input  [1:0]  io_in_pmaCfg_10_A,
  input         io_in_pmaCfg_10_L,
  input         io_in_pmaCfg_10_ATOMIC,
  input         io_in_pmaCfg_10_C,
  input         io_in_pmaCfg_11_R,
  input         io_in_pmaCfg_11_W,
  input         io_in_pmaCfg_11_X,
  input  [1:0]  io_in_pmaCfg_11_A,
  input         io_in_pmaCfg_11_L,
  input         io_in_pmaCfg_11_ATOMIC,
  input         io_in_pmaCfg_11_C,
  input         io_in_pmaCfg_12_R,
  input         io_in_pmaCfg_12_W,
  input         io_in_pmaCfg_12_X,
  input  [1:0]  io_in_pmaCfg_12_A,
  input         io_in_pmaCfg_12_L,
  input         io_in_pmaCfg_12_ATOMIC,
  input         io_in_pmaCfg_12_C,
  input         io_in_pmaCfg_13_R,
  input         io_in_pmaCfg_13_W,
  input         io_in_pmaCfg_13_X,
  input  [1:0]  io_in_pmaCfg_13_A,
  input         io_in_pmaCfg_13_L,
  input         io_in_pmaCfg_13_ATOMIC,
  input         io_in_pmaCfg_13_C,
  input         io_in_pmaCfg_14_R,
  input         io_in_pmaCfg_14_W,
  input         io_in_pmaCfg_14_X,
  input  [1:0]  io_in_pmaCfg_14_A,
  input         io_in_pmaCfg_14_L,
  input         io_in_pmaCfg_14_ATOMIC,
  input         io_in_pmaCfg_14_C,
  input         io_in_pmaCfg_15_R,
  input         io_in_pmaCfg_15_W,
  input         io_in_pmaCfg_15_X,
  input  [1:0]  io_in_pmaCfg_15_A,
  input         io_in_pmaCfg_15_L,
  input         io_in_pmaCfg_15_ATOMIC,
  input         io_in_pmaCfg_15_C,
  output [63:0] io_out_pmaCfgWdata,
  output [63:0] io_out_pmaAddrRData_0,
  output [63:0] io_out_pmaAddrRData_1,
  output [63:0] io_out_pmaAddrRData_2,
  output [63:0] io_out_pmaAddrRData_3,
  output [63:0] io_out_pmaAddrRData_4,
  output [63:0] io_out_pmaAddrRData_5,
  output [63:0] io_out_pmaAddrRData_6,
  output [63:0] io_out_pmaAddrRData_7,
  output [63:0] io_out_pmaAddrRData_8,
  output [63:0] io_out_pmaAddrRData_9,
  output [63:0] io_out_pmaAddrRData_10,
  output [63:0] io_out_pmaAddrRData_11,
  output [63:0] io_out_pmaAddrRData_12,
  output [63:0] io_out_pmaAddrRData_13,
  output [63:0] io_out_pmaAddrRData_14,
  output [63:0] io_out_pmaAddrRData_15
);

  reg  [45:0] pmaAddr_0;
  reg  [45:0] pmaAddr_1;
  reg  [45:0] pmaAddr_2;
  reg  [45:0] pmaAddr_3;
  reg  [45:0] pmaAddr_4;
  reg  [45:0] pmaAddr_5;
  reg  [45:0] pmaAddr_6;
  reg  [45:0] pmaAddr_7;
  reg  [45:0] pmaAddr_8;
  reg  [45:0] pmaAddr_9;
  reg  [45:0] pmaAddr_10;
  reg  [45:0] pmaAddr_11;
  reg  [45:0] pmaAddr_12;
  reg  [45:0] pmaAddr_13;
  reg  [45:0] pmaAddr_14;
  reg  [45:0] pmaAddr_15;
  wire        _GEN = io_in_wen & io_in_addr == 12'h7C0;
  wire        _GEN_0 = io_in_wen & io_in_addr == 12'h7C2;
  wire        _GEN_1 = io_in_addr == 12'h7C8;
  wire        _GEN_2 = io_in_addr == 12'h7C9;
  wire        _GEN_3 = io_in_addr == 12'h7CA;
  wire        _GEN_4 = io_in_addr == 12'h7CB;
  wire        _GEN_5 = io_in_addr == 12'h7CC;
  wire        _GEN_6 = io_in_addr == 12'h7CD;
  wire        _GEN_7 = io_in_addr == 12'h7CE;
  wire        _GEN_8 = io_in_addr == 12'h7CF;
  wire        _GEN_9 = io_in_addr == 12'h7D0;
  wire        _GEN_10 = io_in_addr == 12'h7D1;
  wire        _GEN_11 = io_in_addr == 12'h7D2;
  wire        _GEN_12 = io_in_addr == 12'h7D3;
  wire        _GEN_13 = io_in_addr == 12'h7D4;
  wire        _GEN_14 = io_in_addr == 12'h7D5;
  wire        _GEN_15 = io_in_addr == 12'h7D6;
  wire        _GEN_16 = io_in_addr == 12'h7D7;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      pmaAddr_0 <= 46'h0;
      pmaAddr_1 <= 46'h0;
      pmaAddr_2 <= 46'h0;
      pmaAddr_3 <= 46'h4000000;
      pmaAddr_4 <= 46'h8000000;
      pmaAddr_5 <= 46'hC004000;
      pmaAddr_6 <= 46'hC014000;
      pmaAddr_7 <= 46'hE008000;
      pmaAddr_8 <= 46'hE008400;
      pmaAddr_9 <= 46'hE008800;
      pmaAddr_10 <= 46'hE400000;
      pmaAddr_11 <= 46'hE400800;
      pmaAddr_12 <= 46'hE800000;
      pmaAddr_13 <= 46'h20000000;
      pmaAddr_14 <= 46'h20000000000;
      pmaAddr_15 <= 46'h1FFFFFFFFFFF;
    end
    else begin
      if (~(io_in_wen & _GEN_1) | io_in_pmaCfg_0_L | io_in_pmaCfg_1_L
          & io_in_pmaCfg_1_A == 2'h1) begin
      end
      else
        pmaAddr_0 <= io_in_wdata[45:0];
      if (~(io_in_wen & _GEN_2) | io_in_pmaCfg_1_L | io_in_pmaCfg_2_L
          & io_in_pmaCfg_2_A == 2'h1) begin
      end
      else
        pmaAddr_1 <= io_in_wdata[45:0];
      if (~(io_in_wen & _GEN_3) | io_in_pmaCfg_2_L | io_in_pmaCfg_3_L
          & io_in_pmaCfg_3_A == 2'h1) begin
      end
      else
        pmaAddr_2 <= io_in_wdata[45:0];
      if (~(io_in_wen & _GEN_4) | io_in_pmaCfg_3_L | io_in_pmaCfg_4_L
          & io_in_pmaCfg_4_A == 2'h1) begin
      end
      else
        pmaAddr_3 <= io_in_wdata[45:0];
      if (~(io_in_wen & _GEN_5) | io_in_pmaCfg_4_L | io_in_pmaCfg_5_L
          & io_in_pmaCfg_5_A == 2'h1) begin
      end
      else
        pmaAddr_4 <= io_in_wdata[45:0];
      if (~(io_in_wen & _GEN_6) | io_in_pmaCfg_5_L | io_in_pmaCfg_6_L
          & io_in_pmaCfg_6_A == 2'h1) begin
      end
      else
        pmaAddr_5 <= io_in_wdata[45:0];
      if (~(io_in_wen & _GEN_7) | io_in_pmaCfg_6_L | io_in_pmaCfg_7_L
          & io_in_pmaCfg_7_A == 2'h1) begin
      end
      else
        pmaAddr_6 <= io_in_wdata[45:0];
      if (~(io_in_wen & _GEN_8) | io_in_pmaCfg_7_L | io_in_pmaCfg_8_L
          & io_in_pmaCfg_8_A == 2'h1) begin
      end
      else
        pmaAddr_7 <= io_in_wdata[45:0];
      if (~(io_in_wen & _GEN_9) | io_in_pmaCfg_8_L | io_in_pmaCfg_9_L
          & io_in_pmaCfg_9_A == 2'h1) begin
      end
      else
        pmaAddr_8 <= io_in_wdata[45:0];
      if (~(io_in_wen & _GEN_10) | io_in_pmaCfg_9_L | io_in_pmaCfg_10_L
          & io_in_pmaCfg_10_A == 2'h1) begin
      end
      else
        pmaAddr_9 <= io_in_wdata[45:0];
      if (~(io_in_wen & _GEN_11) | io_in_pmaCfg_10_L | io_in_pmaCfg_11_L
          & io_in_pmaCfg_11_A == 2'h1) begin
      end
      else
        pmaAddr_10 <= io_in_wdata[45:0];
      if (~(io_in_wen & _GEN_12) | io_in_pmaCfg_11_L | io_in_pmaCfg_12_L
          & io_in_pmaCfg_12_A == 2'h1) begin
      end
      else
        pmaAddr_11 <= io_in_wdata[45:0];
      if (~(io_in_wen & _GEN_13) | io_in_pmaCfg_12_L | io_in_pmaCfg_13_L
          & io_in_pmaCfg_13_A == 2'h1) begin
      end
      else
        pmaAddr_12 <= io_in_wdata[45:0];
      if (~(io_in_wen & _GEN_14) | io_in_pmaCfg_13_L | io_in_pmaCfg_14_L
          & io_in_pmaCfg_14_A == 2'h1) begin
      end
      else
        pmaAddr_13 <= io_in_wdata[45:0];
      if (~(io_in_wen & _GEN_15) | io_in_pmaCfg_14_L | io_in_pmaCfg_15_L
          & io_in_pmaCfg_15_A == 2'h1) begin
      end
      else
        pmaAddr_14 <= io_in_wdata[45:0];
      if (~(io_in_wen & _GEN_16) | io_in_pmaCfg_15_L) begin
      end
      else
        pmaAddr_15 <= io_in_wdata[45:0];
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:22];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [4:0] i = 5'h0; i < 5'h17; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        pmaAddr_0 = {_RANDOM[5'h0], _RANDOM[5'h1][13:0]};
        pmaAddr_1 = {_RANDOM[5'h1][31:14], _RANDOM[5'h2][27:0]};
        pmaAddr_2 = {_RANDOM[5'h2][31:28], _RANDOM[5'h3], _RANDOM[5'h4][9:0]};
        pmaAddr_3 = {_RANDOM[5'h4][31:10], _RANDOM[5'h5][23:0]};
        pmaAddr_4 = {_RANDOM[5'h5][31:24], _RANDOM[5'h6], _RANDOM[5'h7][5:0]};
        pmaAddr_5 = {_RANDOM[5'h7][31:6], _RANDOM[5'h8][19:0]};
        pmaAddr_6 = {_RANDOM[5'h8][31:20], _RANDOM[5'h9], _RANDOM[5'hA][1:0]};
        pmaAddr_7 = {_RANDOM[5'hA][31:2], _RANDOM[5'hB][15:0]};
        pmaAddr_8 = {_RANDOM[5'hB][31:16], _RANDOM[5'hC][29:0]};
        pmaAddr_9 = {_RANDOM[5'hC][31:30], _RANDOM[5'hD], _RANDOM[5'hE][11:0]};
        pmaAddr_10 = {_RANDOM[5'hE][31:12], _RANDOM[5'hF][25:0]};
        pmaAddr_11 = {_RANDOM[5'hF][31:26], _RANDOM[5'h10], _RANDOM[5'h11][7:0]};
        pmaAddr_12 = {_RANDOM[5'h11][31:8], _RANDOM[5'h12][21:0]};
        pmaAddr_13 = {_RANDOM[5'h12][31:22], _RANDOM[5'h13], _RANDOM[5'h14][3:0]};
        pmaAddr_14 = {_RANDOM[5'h14][31:4], _RANDOM[5'h15][17:0]};
        pmaAddr_15 = {_RANDOM[5'h15][31:18], _RANDOM[5'h16]};
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        pmaAddr_0 = 46'h0;
        pmaAddr_1 = 46'h0;
        pmaAddr_2 = 46'h0;
        pmaAddr_3 = 46'h4000000;
        pmaAddr_4 = 46'h8000000;
        pmaAddr_5 = 46'hC004000;
        pmaAddr_6 = 46'hC014000;
        pmaAddr_7 = 46'hE008000;
        pmaAddr_8 = 46'hE008400;
        pmaAddr_9 = 46'hE008800;
        pmaAddr_10 = 46'hE400000;
        pmaAddr_11 = 46'hE400800;
        pmaAddr_12 = 46'hE800000;
        pmaAddr_13 = 46'h20000000;
        pmaAddr_14 = 46'h20000000000;
        pmaAddr_15 = 46'h1FFFFFFFFFFF;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_pmaCfgWdata =
    {_GEN_0
       ? (io_in_pmaCfg_15_L ? io_in_pmaCfg_15_L : io_in_wdata[63])
       : _GEN & (io_in_pmaCfg_7_L ? io_in_pmaCfg_7_L : io_in_wdata[63]),
     _GEN_0
       ? (io_in_pmaCfg_15_L ? io_in_pmaCfg_15_C : io_in_wdata[62])
       : _GEN & (io_in_pmaCfg_7_L ? io_in_pmaCfg_7_C : io_in_wdata[62]),
     _GEN_0
       ? (io_in_pmaCfg_15_L ? io_in_pmaCfg_15_ATOMIC : io_in_wdata[61])
       : _GEN & (io_in_pmaCfg_7_L ? io_in_pmaCfg_7_ATOMIC : io_in_wdata[61]),
     _GEN_0
       ? (io_in_pmaCfg_15_L
            ? io_in_pmaCfg_15_A
            : {io_in_wdata[60], |(io_in_wdata[60:59])})
       : _GEN
           ? (io_in_pmaCfg_7_L
                ? io_in_pmaCfg_7_A
                : {io_in_wdata[60], |(io_in_wdata[60:59])})
           : 2'h0,
     _GEN_0
       ? (io_in_pmaCfg_15_L ? io_in_pmaCfg_15_X : io_in_wdata[58])
       : _GEN & (io_in_pmaCfg_7_L ? io_in_pmaCfg_7_X : io_in_wdata[58]),
     _GEN_0
       ? (io_in_pmaCfg_15_L ? io_in_pmaCfg_15_W : io_in_wdata[57] & io_in_wdata[56])
       : _GEN & (io_in_pmaCfg_7_L ? io_in_pmaCfg_7_W : io_in_wdata[57] & io_in_wdata[56]),
     _GEN_0
       ? (io_in_pmaCfg_15_L ? io_in_pmaCfg_15_R : io_in_wdata[56])
       : _GEN & (io_in_pmaCfg_7_L ? io_in_pmaCfg_7_R : io_in_wdata[56]),
     _GEN_0
       ? (io_in_pmaCfg_14_L ? io_in_pmaCfg_14_L : io_in_wdata[55])
       : _GEN & (io_in_pmaCfg_6_L ? io_in_pmaCfg_6_L : io_in_wdata[55]),
     _GEN_0
       ? (io_in_pmaCfg_14_L ? io_in_pmaCfg_14_C : io_in_wdata[54])
       : _GEN & (io_in_pmaCfg_6_L ? io_in_pmaCfg_6_C : io_in_wdata[54]),
     _GEN_0
       ? (io_in_pmaCfg_14_L ? io_in_pmaCfg_14_ATOMIC : io_in_wdata[53])
       : _GEN & (io_in_pmaCfg_6_L ? io_in_pmaCfg_6_ATOMIC : io_in_wdata[53]),
     _GEN_0
       ? (io_in_pmaCfg_14_L
            ? io_in_pmaCfg_14_A
            : {io_in_wdata[52], |(io_in_wdata[52:51])})
       : _GEN
           ? (io_in_pmaCfg_6_L
                ? io_in_pmaCfg_6_A
                : {io_in_wdata[52], |(io_in_wdata[52:51])})
           : 2'h0,
     _GEN_0
       ? (io_in_pmaCfg_14_L ? io_in_pmaCfg_14_X : io_in_wdata[50])
       : _GEN & (io_in_pmaCfg_6_L ? io_in_pmaCfg_6_X : io_in_wdata[50]),
     _GEN_0
       ? (io_in_pmaCfg_14_L ? io_in_pmaCfg_14_W : io_in_wdata[49] & io_in_wdata[48])
       : _GEN & (io_in_pmaCfg_6_L ? io_in_pmaCfg_6_W : io_in_wdata[49] & io_in_wdata[48]),
     _GEN_0
       ? (io_in_pmaCfg_14_L ? io_in_pmaCfg_14_R : io_in_wdata[48])
       : _GEN & (io_in_pmaCfg_6_L ? io_in_pmaCfg_6_R : io_in_wdata[48]),
     _GEN_0
       ? (io_in_pmaCfg_13_L ? io_in_pmaCfg_13_L : io_in_wdata[47])
       : _GEN & (io_in_pmaCfg_5_L ? io_in_pmaCfg_5_L : io_in_wdata[47]),
     _GEN_0
       ? (io_in_pmaCfg_13_L ? io_in_pmaCfg_13_C : io_in_wdata[46])
       : _GEN & (io_in_pmaCfg_5_L ? io_in_pmaCfg_5_C : io_in_wdata[46]),
     _GEN_0
       ? (io_in_pmaCfg_13_L ? io_in_pmaCfg_13_ATOMIC : io_in_wdata[45])
       : _GEN & (io_in_pmaCfg_5_L ? io_in_pmaCfg_5_ATOMIC : io_in_wdata[45]),
     _GEN_0
       ? (io_in_pmaCfg_13_L
            ? io_in_pmaCfg_13_A
            : {io_in_wdata[44], |(io_in_wdata[44:43])})
       : _GEN
           ? (io_in_pmaCfg_5_L
                ? io_in_pmaCfg_5_A
                : {io_in_wdata[44], |(io_in_wdata[44:43])})
           : 2'h0,
     _GEN_0
       ? (io_in_pmaCfg_13_L ? io_in_pmaCfg_13_X : io_in_wdata[42])
       : _GEN & (io_in_pmaCfg_5_L ? io_in_pmaCfg_5_X : io_in_wdata[42]),
     _GEN_0
       ? (io_in_pmaCfg_13_L ? io_in_pmaCfg_13_W : io_in_wdata[41] & io_in_wdata[40])
       : _GEN & (io_in_pmaCfg_5_L ? io_in_pmaCfg_5_W : io_in_wdata[41] & io_in_wdata[40]),
     _GEN_0
       ? (io_in_pmaCfg_13_L ? io_in_pmaCfg_13_R : io_in_wdata[40])
       : _GEN & (io_in_pmaCfg_5_L ? io_in_pmaCfg_5_R : io_in_wdata[40]),
     _GEN_0
       ? (io_in_pmaCfg_12_L ? io_in_pmaCfg_12_L : io_in_wdata[39])
       : _GEN & (io_in_pmaCfg_4_L ? io_in_pmaCfg_4_L : io_in_wdata[39]),
     _GEN_0
       ? (io_in_pmaCfg_12_L ? io_in_pmaCfg_12_C : io_in_wdata[38])
       : _GEN & (io_in_pmaCfg_4_L ? io_in_pmaCfg_4_C : io_in_wdata[38]),
     _GEN_0
       ? (io_in_pmaCfg_12_L ? io_in_pmaCfg_12_ATOMIC : io_in_wdata[37])
       : _GEN & (io_in_pmaCfg_4_L ? io_in_pmaCfg_4_ATOMIC : io_in_wdata[37]),
     _GEN_0
       ? (io_in_pmaCfg_12_L
            ? io_in_pmaCfg_12_A
            : {io_in_wdata[36], |(io_in_wdata[36:35])})
       : _GEN
           ? (io_in_pmaCfg_4_L
                ? io_in_pmaCfg_4_A
                : {io_in_wdata[36], |(io_in_wdata[36:35])})
           : 2'h0,
     _GEN_0
       ? (io_in_pmaCfg_12_L ? io_in_pmaCfg_12_X : io_in_wdata[34])
       : _GEN & (io_in_pmaCfg_4_L ? io_in_pmaCfg_4_X : io_in_wdata[34]),
     _GEN_0
       ? (io_in_pmaCfg_12_L ? io_in_pmaCfg_12_W : io_in_wdata[33] & io_in_wdata[32])
       : _GEN & (io_in_pmaCfg_4_L ? io_in_pmaCfg_4_W : io_in_wdata[33] & io_in_wdata[32]),
     _GEN_0
       ? (io_in_pmaCfg_12_L ? io_in_pmaCfg_12_R : io_in_wdata[32])
       : _GEN & (io_in_pmaCfg_4_L ? io_in_pmaCfg_4_R : io_in_wdata[32]),
     _GEN_0
       ? (io_in_pmaCfg_11_L ? io_in_pmaCfg_11_L : io_in_wdata[31])
       : _GEN & (io_in_pmaCfg_3_L ? io_in_pmaCfg_3_L : io_in_wdata[31]),
     _GEN_0
       ? (io_in_pmaCfg_11_L ? io_in_pmaCfg_11_C : io_in_wdata[30])
       : _GEN & (io_in_pmaCfg_3_L ? io_in_pmaCfg_3_C : io_in_wdata[30]),
     _GEN_0
       ? (io_in_pmaCfg_11_L ? io_in_pmaCfg_11_ATOMIC : io_in_wdata[29])
       : _GEN & (io_in_pmaCfg_3_L ? io_in_pmaCfg_3_ATOMIC : io_in_wdata[29]),
     _GEN_0
       ? (io_in_pmaCfg_11_L
            ? io_in_pmaCfg_11_A
            : {io_in_wdata[28], |(io_in_wdata[28:27])})
       : _GEN
           ? (io_in_pmaCfg_3_L
                ? io_in_pmaCfg_3_A
                : {io_in_wdata[28], |(io_in_wdata[28:27])})
           : 2'h0,
     _GEN_0
       ? (io_in_pmaCfg_11_L ? io_in_pmaCfg_11_X : io_in_wdata[26])
       : _GEN & (io_in_pmaCfg_3_L ? io_in_pmaCfg_3_X : io_in_wdata[26]),
     _GEN_0
       ? (io_in_pmaCfg_11_L ? io_in_pmaCfg_11_W : io_in_wdata[25] & io_in_wdata[24])
       : _GEN & (io_in_pmaCfg_3_L ? io_in_pmaCfg_3_W : io_in_wdata[25] & io_in_wdata[24]),
     _GEN_0
       ? (io_in_pmaCfg_11_L ? io_in_pmaCfg_11_R : io_in_wdata[24])
       : _GEN & (io_in_pmaCfg_3_L ? io_in_pmaCfg_3_R : io_in_wdata[24]),
     _GEN_0
       ? (io_in_pmaCfg_10_L ? io_in_pmaCfg_10_L : io_in_wdata[23])
       : _GEN & (io_in_pmaCfg_2_L ? io_in_pmaCfg_2_L : io_in_wdata[23]),
     _GEN_0
       ? (io_in_pmaCfg_10_L ? io_in_pmaCfg_10_C : io_in_wdata[22])
       : _GEN & (io_in_pmaCfg_2_L ? io_in_pmaCfg_2_C : io_in_wdata[22]),
     _GEN_0
       ? (io_in_pmaCfg_10_L ? io_in_pmaCfg_10_ATOMIC : io_in_wdata[21])
       : _GEN & (io_in_pmaCfg_2_L ? io_in_pmaCfg_2_ATOMIC : io_in_wdata[21]),
     _GEN_0
       ? (io_in_pmaCfg_10_L
            ? io_in_pmaCfg_10_A
            : {io_in_wdata[20], |(io_in_wdata[20:19])})
       : _GEN
           ? (io_in_pmaCfg_2_L
                ? io_in_pmaCfg_2_A
                : {io_in_wdata[20], |(io_in_wdata[20:19])})
           : 2'h0,
     _GEN_0
       ? (io_in_pmaCfg_10_L ? io_in_pmaCfg_10_X : io_in_wdata[18])
       : _GEN & (io_in_pmaCfg_2_L ? io_in_pmaCfg_2_X : io_in_wdata[18]),
     _GEN_0
       ? (io_in_pmaCfg_10_L ? io_in_pmaCfg_10_W : io_in_wdata[17] & io_in_wdata[16])
       : _GEN & (io_in_pmaCfg_2_L ? io_in_pmaCfg_2_W : io_in_wdata[17] & io_in_wdata[16]),
     _GEN_0
       ? (io_in_pmaCfg_10_L ? io_in_pmaCfg_10_R : io_in_wdata[16])
       : _GEN & (io_in_pmaCfg_2_L ? io_in_pmaCfg_2_R : io_in_wdata[16]),
     _GEN_0
       ? (io_in_pmaCfg_9_L ? io_in_pmaCfg_9_L : io_in_wdata[15])
       : _GEN & (io_in_pmaCfg_1_L ? io_in_pmaCfg_1_L : io_in_wdata[15]),
     _GEN_0
       ? (io_in_pmaCfg_9_L ? io_in_pmaCfg_9_C : io_in_wdata[14])
       : _GEN & (io_in_pmaCfg_1_L ? io_in_pmaCfg_1_C : io_in_wdata[14]),
     _GEN_0
       ? (io_in_pmaCfg_9_L ? io_in_pmaCfg_9_ATOMIC : io_in_wdata[13])
       : _GEN & (io_in_pmaCfg_1_L ? io_in_pmaCfg_1_ATOMIC : io_in_wdata[13]),
     _GEN_0
       ? (io_in_pmaCfg_9_L ? io_in_pmaCfg_9_A : {io_in_wdata[12], |(io_in_wdata[12:11])})
       : _GEN
           ? (io_in_pmaCfg_1_L
                ? io_in_pmaCfg_1_A
                : {io_in_wdata[12], |(io_in_wdata[12:11])})
           : 2'h0,
     _GEN_0
       ? (io_in_pmaCfg_9_L ? io_in_pmaCfg_9_X : io_in_wdata[10])
       : _GEN & (io_in_pmaCfg_1_L ? io_in_pmaCfg_1_X : io_in_wdata[10]),
     _GEN_0
       ? (io_in_pmaCfg_9_L ? io_in_pmaCfg_9_W : io_in_wdata[9] & io_in_wdata[8])
       : _GEN & (io_in_pmaCfg_1_L ? io_in_pmaCfg_1_W : io_in_wdata[9] & io_in_wdata[8]),
     _GEN_0
       ? (io_in_pmaCfg_9_L ? io_in_pmaCfg_9_R : io_in_wdata[8])
       : _GEN & (io_in_pmaCfg_1_L ? io_in_pmaCfg_1_R : io_in_wdata[8]),
     _GEN_0
       ? (io_in_pmaCfg_8_L ? io_in_pmaCfg_8_L : io_in_wdata[7])
       : _GEN & (io_in_pmaCfg_0_L ? io_in_pmaCfg_0_L : io_in_wdata[7]),
     _GEN_0
       ? (io_in_pmaCfg_8_L ? io_in_pmaCfg_8_C : io_in_wdata[6])
       : _GEN & (io_in_pmaCfg_0_L ? io_in_pmaCfg_0_C : io_in_wdata[6]),
     _GEN_0
       ? (io_in_pmaCfg_8_L ? io_in_pmaCfg_8_ATOMIC : io_in_wdata[5])
       : _GEN & (io_in_pmaCfg_0_L ? io_in_pmaCfg_0_ATOMIC : io_in_wdata[5]),
     _GEN_0
       ? (io_in_pmaCfg_8_L ? io_in_pmaCfg_8_A : {io_in_wdata[4], |(io_in_wdata[4:3])})
       : _GEN
           ? (io_in_pmaCfg_0_L ? io_in_pmaCfg_0_A : {io_in_wdata[4], |(io_in_wdata[4:3])})
           : 2'h0,
     _GEN_0
       ? (io_in_pmaCfg_8_L ? io_in_pmaCfg_8_X : io_in_wdata[2])
       : _GEN & (io_in_pmaCfg_0_L ? io_in_pmaCfg_0_X : io_in_wdata[2]),
     _GEN_0
       ? (io_in_pmaCfg_8_L ? io_in_pmaCfg_8_W : io_in_wdata[1] & io_in_wdata[0])
       : _GEN & (io_in_pmaCfg_0_L ? io_in_pmaCfg_0_W : io_in_wdata[1] & io_in_wdata[0]),
     _GEN_0
       ? (io_in_pmaCfg_8_L ? io_in_pmaCfg_8_R : io_in_wdata[0])
       : _GEN & (io_in_pmaCfg_0_L ? io_in_pmaCfg_0_R : io_in_wdata[0])};
  assign io_out_pmaAddrRData_0 =
    {18'h0,
     io_in_ren & _GEN_1
       ? (io_in_pmaCfg_0_A[1] ? {pmaAddr_0[45:9], 9'h1FF} : {pmaAddr_0[45:10], 10'h0})
       : pmaAddr_0};
  assign io_out_pmaAddrRData_1 =
    {18'h0,
     io_in_ren & _GEN_2
       ? (io_in_pmaCfg_1_A[1] ? {pmaAddr_1[45:9], 9'h1FF} : {pmaAddr_1[45:10], 10'h0})
       : pmaAddr_1};
  assign io_out_pmaAddrRData_2 =
    {18'h0,
     io_in_ren & _GEN_3
       ? (io_in_pmaCfg_2_A[1] ? {pmaAddr_2[45:9], 9'h1FF} : {pmaAddr_2[45:10], 10'h0})
       : pmaAddr_2};
  assign io_out_pmaAddrRData_3 =
    {18'h0,
     io_in_ren & _GEN_4
       ? (io_in_pmaCfg_3_A[1] ? {pmaAddr_3[45:9], 9'h1FF} : {pmaAddr_3[45:10], 10'h0})
       : pmaAddr_3};
  assign io_out_pmaAddrRData_4 =
    {18'h0,
     io_in_ren & _GEN_5
       ? (io_in_pmaCfg_4_A[1] ? {pmaAddr_4[45:9], 9'h1FF} : {pmaAddr_4[45:10], 10'h0})
       : pmaAddr_4};
  assign io_out_pmaAddrRData_5 =
    {18'h0,
     io_in_ren & _GEN_6
       ? (io_in_pmaCfg_5_A[1] ? {pmaAddr_5[45:9], 9'h1FF} : {pmaAddr_5[45:10], 10'h0})
       : pmaAddr_5};
  assign io_out_pmaAddrRData_6 =
    {18'h0,
     io_in_ren & _GEN_7
       ? (io_in_pmaCfg_6_A[1] ? {pmaAddr_6[45:9], 9'h1FF} : {pmaAddr_6[45:10], 10'h0})
       : pmaAddr_6};
  assign io_out_pmaAddrRData_7 =
    {18'h0,
     io_in_ren & _GEN_8
       ? (io_in_pmaCfg_7_A[1] ? {pmaAddr_7[45:9], 9'h1FF} : {pmaAddr_7[45:10], 10'h0})
       : pmaAddr_7};
  assign io_out_pmaAddrRData_8 =
    {18'h0,
     io_in_ren & _GEN_9
       ? (io_in_pmaCfg_8_A[1] ? {pmaAddr_8[45:9], 9'h1FF} : {pmaAddr_8[45:10], 10'h0})
       : pmaAddr_8};
  assign io_out_pmaAddrRData_9 =
    {18'h0,
     io_in_ren & _GEN_10
       ? (io_in_pmaCfg_9_A[1] ? {pmaAddr_9[45:9], 9'h1FF} : {pmaAddr_9[45:10], 10'h0})
       : pmaAddr_9};
  assign io_out_pmaAddrRData_10 =
    {18'h0,
     io_in_ren & _GEN_11
       ? (io_in_pmaCfg_10_A[1] ? {pmaAddr_10[45:9], 9'h1FF} : {pmaAddr_10[45:10], 10'h0})
       : pmaAddr_10};
  assign io_out_pmaAddrRData_11 =
    {18'h0,
     io_in_ren & _GEN_12
       ? (io_in_pmaCfg_11_A[1] ? {pmaAddr_11[45:9], 9'h1FF} : {pmaAddr_11[45:10], 10'h0})
       : pmaAddr_11};
  assign io_out_pmaAddrRData_12 =
    {18'h0,
     io_in_ren & _GEN_13
       ? (io_in_pmaCfg_12_A[1] ? {pmaAddr_12[45:9], 9'h1FF} : {pmaAddr_12[45:10], 10'h0})
       : pmaAddr_12};
  assign io_out_pmaAddrRData_13 =
    {18'h0,
     io_in_ren & _GEN_14
       ? (io_in_pmaCfg_13_A[1] ? {pmaAddr_13[45:9], 9'h1FF} : {pmaAddr_13[45:10], 10'h0})
       : pmaAddr_13};
  assign io_out_pmaAddrRData_14 =
    {18'h0,
     io_in_ren & _GEN_15
       ? (io_in_pmaCfg_14_A[1] ? {pmaAddr_14[45:9], 9'h1FF} : {pmaAddr_14[45:10], 10'h0})
       : pmaAddr_14};
  assign io_out_pmaAddrRData_15 =
    {18'h0,
     io_in_ren & _GEN_16
       ? (io_in_pmaCfg_15_A[1] ? {pmaAddr_15[45:9], 9'h1FF} : {pmaAddr_15[45:10], 10'h0})
       : pmaAddr_15};
endmodule

