// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module SimMMIO(
  input         clock,
  input         reset,
  output        io_axi4_0_aw_ready,
  input         io_axi4_0_aw_valid,
  input  [1:0]  io_axi4_0_aw_bits_id,
  input  [30:0] io_axi4_0_aw_bits_addr,
  input  [7:0]  io_axi4_0_aw_bits_len,
  input  [2:0]  io_axi4_0_aw_bits_size,
  input  [1:0]  io_axi4_0_aw_bits_burst,
  input         io_axi4_0_aw_bits_lock,
  input  [3:0]  io_axi4_0_aw_bits_cache,
  input  [2:0]  io_axi4_0_aw_bits_prot,
  input  [3:0]  io_axi4_0_aw_bits_qos,
  output        io_axi4_0_w_ready,
  input         io_axi4_0_w_valid,
  input  [63:0] io_axi4_0_w_bits_data,
  input  [7:0]  io_axi4_0_w_bits_strb,
  input         io_axi4_0_w_bits_last,
  input         io_axi4_0_b_ready,
  output        io_axi4_0_b_valid,
  output [1:0]  io_axi4_0_b_bits_id,
  output [1:0]  io_axi4_0_b_bits_resp,
  output        io_axi4_0_ar_ready,
  input         io_axi4_0_ar_valid,
  input  [1:0]  io_axi4_0_ar_bits_id,
  input  [30:0] io_axi4_0_ar_bits_addr,
  input  [7:0]  io_axi4_0_ar_bits_len,
  input  [2:0]  io_axi4_0_ar_bits_size,
  input  [1:0]  io_axi4_0_ar_bits_burst,
  input         io_axi4_0_ar_bits_lock,
  input  [3:0]  io_axi4_0_ar_bits_cache,
  input  [2:0]  io_axi4_0_ar_bits_prot,
  input  [3:0]  io_axi4_0_ar_bits_qos,
  input         io_axi4_0_r_ready,
  output        io_axi4_0_r_valid,
  output [1:0]  io_axi4_0_r_bits_id,
  output [63:0] io_axi4_0_r_bits_data,
  output [1:0]  io_axi4_0_r_bits_resp,
  output        io_axi4_0_r_bits_last,
  output        io_uart_out_valid,
  output [7:0]  io_uart_out_ch,
  output        io_uart_in_valid,
  input  [7:0]  io_uart_in_ch,
  output [63:0] io_interrupt_intrVec
);

  wire        _axi4xbar_auto_out_4_aw_valid;
  wire [1:0]  _axi4xbar_auto_out_4_aw_bits_id;
  wire [30:0] _axi4xbar_auto_out_4_aw_bits_addr;
  wire [7:0]  _axi4xbar_auto_out_4_aw_bits_len;
  wire [2:0]  _axi4xbar_auto_out_4_aw_bits_size;
  wire [1:0]  _axi4xbar_auto_out_4_aw_bits_burst;
  wire        _axi4xbar_auto_out_4_aw_bits_lock;
  wire [3:0]  _axi4xbar_auto_out_4_aw_bits_cache;
  wire [2:0]  _axi4xbar_auto_out_4_aw_bits_prot;
  wire [3:0]  _axi4xbar_auto_out_4_aw_bits_qos;
  wire        _axi4xbar_auto_out_4_w_valid;
  wire [63:0] _axi4xbar_auto_out_4_w_bits_data;
  wire [7:0]  _axi4xbar_auto_out_4_w_bits_strb;
  wire        _axi4xbar_auto_out_4_w_bits_last;
  wire        _axi4xbar_auto_out_4_b_ready;
  wire        _axi4xbar_auto_out_4_ar_valid;
  wire [1:0]  _axi4xbar_auto_out_4_ar_bits_id;
  wire [30:0] _axi4xbar_auto_out_4_ar_bits_addr;
  wire [7:0]  _axi4xbar_auto_out_4_ar_bits_len;
  wire [2:0]  _axi4xbar_auto_out_4_ar_bits_size;
  wire [1:0]  _axi4xbar_auto_out_4_ar_bits_burst;
  wire        _axi4xbar_auto_out_4_ar_bits_lock;
  wire [3:0]  _axi4xbar_auto_out_4_ar_bits_cache;
  wire [2:0]  _axi4xbar_auto_out_4_ar_bits_prot;
  wire [3:0]  _axi4xbar_auto_out_4_ar_bits_qos;
  wire        _axi4xbar_auto_out_4_r_ready;
  wire        _axi4xbar_auto_out_3_aw_valid;
  wire [1:0]  _axi4xbar_auto_out_3_aw_bits_id;
  wire [30:0] _axi4xbar_auto_out_3_aw_bits_addr;
  wire [7:0]  _axi4xbar_auto_out_3_aw_bits_len;
  wire [2:0]  _axi4xbar_auto_out_3_aw_bits_size;
  wire [1:0]  _axi4xbar_auto_out_3_aw_bits_burst;
  wire        _axi4xbar_auto_out_3_aw_bits_lock;
  wire [3:0]  _axi4xbar_auto_out_3_aw_bits_cache;
  wire [2:0]  _axi4xbar_auto_out_3_aw_bits_prot;
  wire [3:0]  _axi4xbar_auto_out_3_aw_bits_qos;
  wire        _axi4xbar_auto_out_3_w_valid;
  wire [63:0] _axi4xbar_auto_out_3_w_bits_data;
  wire [7:0]  _axi4xbar_auto_out_3_w_bits_strb;
  wire        _axi4xbar_auto_out_3_w_bits_last;
  wire        _axi4xbar_auto_out_3_b_ready;
  wire        _axi4xbar_auto_out_3_ar_valid;
  wire [1:0]  _axi4xbar_auto_out_3_ar_bits_id;
  wire [30:0] _axi4xbar_auto_out_3_ar_bits_addr;
  wire [7:0]  _axi4xbar_auto_out_3_ar_bits_len;
  wire [2:0]  _axi4xbar_auto_out_3_ar_bits_size;
  wire [1:0]  _axi4xbar_auto_out_3_ar_bits_burst;
  wire        _axi4xbar_auto_out_3_ar_bits_lock;
  wire [3:0]  _axi4xbar_auto_out_3_ar_bits_cache;
  wire [2:0]  _axi4xbar_auto_out_3_ar_bits_prot;
  wire [3:0]  _axi4xbar_auto_out_3_ar_bits_qos;
  wire        _axi4xbar_auto_out_3_r_ready;
  wire        _axi4xbar_auto_out_2_aw_valid;
  wire [1:0]  _axi4xbar_auto_out_2_aw_bits_id;
  wire [30:0] _axi4xbar_auto_out_2_aw_bits_addr;
  wire [7:0]  _axi4xbar_auto_out_2_aw_bits_len;
  wire [2:0]  _axi4xbar_auto_out_2_aw_bits_size;
  wire [1:0]  _axi4xbar_auto_out_2_aw_bits_burst;
  wire        _axi4xbar_auto_out_2_aw_bits_lock;
  wire [3:0]  _axi4xbar_auto_out_2_aw_bits_cache;
  wire [2:0]  _axi4xbar_auto_out_2_aw_bits_prot;
  wire [3:0]  _axi4xbar_auto_out_2_aw_bits_qos;
  wire        _axi4xbar_auto_out_2_w_valid;
  wire [63:0] _axi4xbar_auto_out_2_w_bits_data;
  wire [7:0]  _axi4xbar_auto_out_2_w_bits_strb;
  wire        _axi4xbar_auto_out_2_w_bits_last;
  wire        _axi4xbar_auto_out_2_b_ready;
  wire        _axi4xbar_auto_out_2_ar_valid;
  wire [1:0]  _axi4xbar_auto_out_2_ar_bits_id;
  wire [30:0] _axi4xbar_auto_out_2_ar_bits_addr;
  wire [7:0]  _axi4xbar_auto_out_2_ar_bits_len;
  wire [2:0]  _axi4xbar_auto_out_2_ar_bits_size;
  wire [1:0]  _axi4xbar_auto_out_2_ar_bits_burst;
  wire        _axi4xbar_auto_out_2_ar_bits_lock;
  wire [3:0]  _axi4xbar_auto_out_2_ar_bits_cache;
  wire [2:0]  _axi4xbar_auto_out_2_ar_bits_prot;
  wire [3:0]  _axi4xbar_auto_out_2_ar_bits_qos;
  wire        _axi4xbar_auto_out_2_r_ready;
  wire        _axi4xbar_auto_out_1_aw_valid;
  wire [1:0]  _axi4xbar_auto_out_1_aw_bits_id;
  wire [28:0] _axi4xbar_auto_out_1_aw_bits_addr;
  wire [7:0]  _axi4xbar_auto_out_1_aw_bits_len;
  wire [2:0]  _axi4xbar_auto_out_1_aw_bits_size;
  wire [1:0]  _axi4xbar_auto_out_1_aw_bits_burst;
  wire        _axi4xbar_auto_out_1_aw_bits_lock;
  wire [3:0]  _axi4xbar_auto_out_1_aw_bits_cache;
  wire [2:0]  _axi4xbar_auto_out_1_aw_bits_prot;
  wire [3:0]  _axi4xbar_auto_out_1_aw_bits_qos;
  wire        _axi4xbar_auto_out_1_w_valid;
  wire [63:0] _axi4xbar_auto_out_1_w_bits_data;
  wire [7:0]  _axi4xbar_auto_out_1_w_bits_strb;
  wire        _axi4xbar_auto_out_1_w_bits_last;
  wire        _axi4xbar_auto_out_1_b_ready;
  wire        _axi4xbar_auto_out_1_ar_valid;
  wire [1:0]  _axi4xbar_auto_out_1_ar_bits_id;
  wire [28:0] _axi4xbar_auto_out_1_ar_bits_addr;
  wire [7:0]  _axi4xbar_auto_out_1_ar_bits_len;
  wire [2:0]  _axi4xbar_auto_out_1_ar_bits_size;
  wire [1:0]  _axi4xbar_auto_out_1_ar_bits_burst;
  wire        _axi4xbar_auto_out_1_ar_bits_lock;
  wire [3:0]  _axi4xbar_auto_out_1_ar_bits_cache;
  wire [2:0]  _axi4xbar_auto_out_1_ar_bits_prot;
  wire [3:0]  _axi4xbar_auto_out_1_ar_bits_qos;
  wire        _axi4xbar_auto_out_1_r_ready;
  wire        _axi4xbar_auto_out_0_aw_valid;
  wire [1:0]  _axi4xbar_auto_out_0_aw_bits_id;
  wire [30:0] _axi4xbar_auto_out_0_aw_bits_addr;
  wire [7:0]  _axi4xbar_auto_out_0_aw_bits_len;
  wire [2:0]  _axi4xbar_auto_out_0_aw_bits_size;
  wire [1:0]  _axi4xbar_auto_out_0_aw_bits_burst;
  wire        _axi4xbar_auto_out_0_aw_bits_lock;
  wire [3:0]  _axi4xbar_auto_out_0_aw_bits_cache;
  wire [2:0]  _axi4xbar_auto_out_0_aw_bits_prot;
  wire [3:0]  _axi4xbar_auto_out_0_aw_bits_qos;
  wire        _axi4xbar_auto_out_0_w_valid;
  wire [63:0] _axi4xbar_auto_out_0_w_bits_data;
  wire [7:0]  _axi4xbar_auto_out_0_w_bits_strb;
  wire        _axi4xbar_auto_out_0_w_bits_last;
  wire        _axi4xbar_auto_out_0_b_ready;
  wire        _axi4xbar_auto_out_0_ar_valid;
  wire [1:0]  _axi4xbar_auto_out_0_ar_bits_id;
  wire [30:0] _axi4xbar_auto_out_0_ar_bits_addr;
  wire [7:0]  _axi4xbar_auto_out_0_ar_bits_len;
  wire [2:0]  _axi4xbar_auto_out_0_ar_bits_size;
  wire [1:0]  _axi4xbar_auto_out_0_ar_bits_burst;
  wire        _axi4xbar_auto_out_0_ar_bits_lock;
  wire [3:0]  _axi4xbar_auto_out_0_ar_bits_cache;
  wire [2:0]  _axi4xbar_auto_out_0_ar_bits_prot;
  wire [3:0]  _axi4xbar_auto_out_0_ar_bits_qos;
  wire        _axi4xbar_auto_out_0_r_ready;
  wire        _error_auto_in_aw_ready;
  wire        _error_auto_in_w_ready;
  wire        _error_auto_in_b_valid;
  wire [1:0]  _error_auto_in_b_bits_id;
  wire        _error_auto_in_ar_ready;
  wire        _error_auto_in_r_valid;
  wire [1:0]  _error_auto_in_r_bits_id;
  wire        _intrGen_auto_in_aw_ready;
  wire        _intrGen_auto_in_w_ready;
  wire        _intrGen_auto_in_b_valid;
  wire [1:0]  _intrGen_auto_in_b_bits_id;
  wire [1:0]  _intrGen_auto_in_b_bits_resp;
  wire        _intrGen_auto_in_ar_ready;
  wire        _intrGen_auto_in_r_valid;
  wire [1:0]  _intrGen_auto_in_r_bits_id;
  wire [63:0] _intrGen_auto_in_r_bits_data;
  wire [1:0]  _intrGen_auto_in_r_bits_resp;
  wire        _intrGen_auto_in_r_bits_last;
  wire        _sd_auto_in_aw_ready;
  wire        _sd_auto_in_w_ready;
  wire        _sd_auto_in_b_valid;
  wire [1:0]  _sd_auto_in_b_bits_id;
  wire [1:0]  _sd_auto_in_b_bits_resp;
  wire        _sd_auto_in_ar_ready;
  wire        _sd_auto_in_r_valid;
  wire [1:0]  _sd_auto_in_r_bits_id;
  wire [63:0] _sd_auto_in_r_bits_data;
  wire [1:0]  _sd_auto_in_r_bits_resp;
  wire        _sd_auto_in_r_bits_last;
  wire        _uart_auto_in_aw_ready;
  wire        _uart_auto_in_w_ready;
  wire        _uart_auto_in_b_valid;
  wire [1:0]  _uart_auto_in_b_bits_id;
  wire [1:0]  _uart_auto_in_b_bits_resp;
  wire        _uart_auto_in_ar_ready;
  wire        _uart_auto_in_r_valid;
  wire [1:0]  _uart_auto_in_r_bits_id;
  wire [63:0] _uart_auto_in_r_bits_data;
  wire [1:0]  _uart_auto_in_r_bits_resp;
  wire        _uart_auto_in_r_bits_last;
  wire        _flash_auto_in_aw_ready;
  wire        _flash_auto_in_w_ready;
  wire        _flash_auto_in_b_valid;
  wire [1:0]  _flash_auto_in_b_bits_id;
  wire [1:0]  _flash_auto_in_b_bits_resp;
  wire        _flash_auto_in_ar_ready;
  wire        _flash_auto_in_r_valid;
  wire [1:0]  _flash_auto_in_r_bits_id;
  wire [63:0] _flash_auto_in_r_bits_data;
  wire [1:0]  _flash_auto_in_r_bits_resp;
  wire        _flash_auto_in_r_bits_last;
  AXI4Flash flash (
    .clock                 (clock),
    .reset                 (reset),
    .auto_in_aw_ready      (_flash_auto_in_aw_ready),
    .auto_in_aw_valid      (_axi4xbar_auto_out_1_aw_valid),
    .auto_in_aw_bits_id    (_axi4xbar_auto_out_1_aw_bits_id),
    .auto_in_aw_bits_addr  (_axi4xbar_auto_out_1_aw_bits_addr),
    .auto_in_aw_bits_len   (_axi4xbar_auto_out_1_aw_bits_len),
    .auto_in_aw_bits_size  (_axi4xbar_auto_out_1_aw_bits_size),
    .auto_in_aw_bits_burst (_axi4xbar_auto_out_1_aw_bits_burst),
    .auto_in_aw_bits_lock  (_axi4xbar_auto_out_1_aw_bits_lock),
    .auto_in_aw_bits_cache (_axi4xbar_auto_out_1_aw_bits_cache),
    .auto_in_aw_bits_prot  (_axi4xbar_auto_out_1_aw_bits_prot),
    .auto_in_aw_bits_qos   (_axi4xbar_auto_out_1_aw_bits_qos),
    .auto_in_w_ready       (_flash_auto_in_w_ready),
    .auto_in_w_valid       (_axi4xbar_auto_out_1_w_valid),
    .auto_in_w_bits_data   (_axi4xbar_auto_out_1_w_bits_data),
    .auto_in_w_bits_strb   (_axi4xbar_auto_out_1_w_bits_strb),
    .auto_in_w_bits_last   (_axi4xbar_auto_out_1_w_bits_last),
    .auto_in_b_ready       (_axi4xbar_auto_out_1_b_ready),
    .auto_in_b_valid       (_flash_auto_in_b_valid),
    .auto_in_b_bits_id     (_flash_auto_in_b_bits_id),
    .auto_in_b_bits_resp   (_flash_auto_in_b_bits_resp),
    .auto_in_ar_ready      (_flash_auto_in_ar_ready),
    .auto_in_ar_valid      (_axi4xbar_auto_out_1_ar_valid),
    .auto_in_ar_bits_id    (_axi4xbar_auto_out_1_ar_bits_id),
    .auto_in_ar_bits_addr  (_axi4xbar_auto_out_1_ar_bits_addr),
    .auto_in_ar_bits_len   (_axi4xbar_auto_out_1_ar_bits_len),
    .auto_in_ar_bits_size  (_axi4xbar_auto_out_1_ar_bits_size),
    .auto_in_ar_bits_burst (_axi4xbar_auto_out_1_ar_bits_burst),
    .auto_in_ar_bits_lock  (_axi4xbar_auto_out_1_ar_bits_lock),
    .auto_in_ar_bits_cache (_axi4xbar_auto_out_1_ar_bits_cache),
    .auto_in_ar_bits_prot  (_axi4xbar_auto_out_1_ar_bits_prot),
    .auto_in_ar_bits_qos   (_axi4xbar_auto_out_1_ar_bits_qos),
    .auto_in_r_ready       (_axi4xbar_auto_out_1_r_ready),
    .auto_in_r_valid       (_flash_auto_in_r_valid),
    .auto_in_r_bits_id     (_flash_auto_in_r_bits_id),
    .auto_in_r_bits_data   (_flash_auto_in_r_bits_data),
    .auto_in_r_bits_resp   (_flash_auto_in_r_bits_resp),
    .auto_in_r_bits_last   (_flash_auto_in_r_bits_last)
  );
  AXI4UART uart (
    .clock                 (clock),
    .reset                 (reset),
    .auto_in_aw_ready      (_uart_auto_in_aw_ready),
    .auto_in_aw_valid      (_axi4xbar_auto_out_0_aw_valid),
    .auto_in_aw_bits_id    (_axi4xbar_auto_out_0_aw_bits_id),
    .auto_in_aw_bits_addr  (_axi4xbar_auto_out_0_aw_bits_addr),
    .auto_in_aw_bits_len   (_axi4xbar_auto_out_0_aw_bits_len),
    .auto_in_aw_bits_size  (_axi4xbar_auto_out_0_aw_bits_size),
    .auto_in_aw_bits_burst (_axi4xbar_auto_out_0_aw_bits_burst),
    .auto_in_aw_bits_lock  (_axi4xbar_auto_out_0_aw_bits_lock),
    .auto_in_aw_bits_cache (_axi4xbar_auto_out_0_aw_bits_cache),
    .auto_in_aw_bits_prot  (_axi4xbar_auto_out_0_aw_bits_prot),
    .auto_in_aw_bits_qos   (_axi4xbar_auto_out_0_aw_bits_qos),
    .auto_in_w_ready       (_uart_auto_in_w_ready),
    .auto_in_w_valid       (_axi4xbar_auto_out_0_w_valid),
    .auto_in_w_bits_data   (_axi4xbar_auto_out_0_w_bits_data),
    .auto_in_w_bits_strb   (_axi4xbar_auto_out_0_w_bits_strb),
    .auto_in_w_bits_last   (_axi4xbar_auto_out_0_w_bits_last),
    .auto_in_b_ready       (_axi4xbar_auto_out_0_b_ready),
    .auto_in_b_valid       (_uart_auto_in_b_valid),
    .auto_in_b_bits_id     (_uart_auto_in_b_bits_id),
    .auto_in_b_bits_resp   (_uart_auto_in_b_bits_resp),
    .auto_in_ar_ready      (_uart_auto_in_ar_ready),
    .auto_in_ar_valid      (_axi4xbar_auto_out_0_ar_valid),
    .auto_in_ar_bits_id    (_axi4xbar_auto_out_0_ar_bits_id),
    .auto_in_ar_bits_addr  (_axi4xbar_auto_out_0_ar_bits_addr),
    .auto_in_ar_bits_len   (_axi4xbar_auto_out_0_ar_bits_len),
    .auto_in_ar_bits_size  (_axi4xbar_auto_out_0_ar_bits_size),
    .auto_in_ar_bits_burst (_axi4xbar_auto_out_0_ar_bits_burst),
    .auto_in_ar_bits_lock  (_axi4xbar_auto_out_0_ar_bits_lock),
    .auto_in_ar_bits_cache (_axi4xbar_auto_out_0_ar_bits_cache),
    .auto_in_ar_bits_prot  (_axi4xbar_auto_out_0_ar_bits_prot),
    .auto_in_ar_bits_qos   (_axi4xbar_auto_out_0_ar_bits_qos),
    .auto_in_r_ready       (_axi4xbar_auto_out_0_r_ready),
    .auto_in_r_valid       (_uart_auto_in_r_valid),
    .auto_in_r_bits_id     (_uart_auto_in_r_bits_id),
    .auto_in_r_bits_data   (_uart_auto_in_r_bits_data),
    .auto_in_r_bits_resp   (_uart_auto_in_r_bits_resp),
    .auto_in_r_bits_last   (_uart_auto_in_r_bits_last),
    .io_extra_out_valid    (io_uart_out_valid),
    .io_extra_out_ch       (io_uart_out_ch),
    .io_extra_in_valid     (io_uart_in_valid),
    .io_extra_in_ch        (io_uart_in_ch)
  );
  AXI4DummySD sd (
    .clock                 (clock),
    .reset                 (reset),
    .auto_in_aw_ready      (_sd_auto_in_aw_ready),
    .auto_in_aw_valid      (_axi4xbar_auto_out_2_aw_valid),
    .auto_in_aw_bits_id    (_axi4xbar_auto_out_2_aw_bits_id),
    .auto_in_aw_bits_addr  (_axi4xbar_auto_out_2_aw_bits_addr),
    .auto_in_aw_bits_len   (_axi4xbar_auto_out_2_aw_bits_len),
    .auto_in_aw_bits_size  (_axi4xbar_auto_out_2_aw_bits_size),
    .auto_in_aw_bits_burst (_axi4xbar_auto_out_2_aw_bits_burst),
    .auto_in_aw_bits_lock  (_axi4xbar_auto_out_2_aw_bits_lock),
    .auto_in_aw_bits_cache (_axi4xbar_auto_out_2_aw_bits_cache),
    .auto_in_aw_bits_prot  (_axi4xbar_auto_out_2_aw_bits_prot),
    .auto_in_aw_bits_qos   (_axi4xbar_auto_out_2_aw_bits_qos),
    .auto_in_w_ready       (_sd_auto_in_w_ready),
    .auto_in_w_valid       (_axi4xbar_auto_out_2_w_valid),
    .auto_in_w_bits_data   (_axi4xbar_auto_out_2_w_bits_data),
    .auto_in_w_bits_strb   (_axi4xbar_auto_out_2_w_bits_strb),
    .auto_in_w_bits_last   (_axi4xbar_auto_out_2_w_bits_last),
    .auto_in_b_ready       (_axi4xbar_auto_out_2_b_ready),
    .auto_in_b_valid       (_sd_auto_in_b_valid),
    .auto_in_b_bits_id     (_sd_auto_in_b_bits_id),
    .auto_in_b_bits_resp   (_sd_auto_in_b_bits_resp),
    .auto_in_ar_ready      (_sd_auto_in_ar_ready),
    .auto_in_ar_valid      (_axi4xbar_auto_out_2_ar_valid),
    .auto_in_ar_bits_id    (_axi4xbar_auto_out_2_ar_bits_id),
    .auto_in_ar_bits_addr  (_axi4xbar_auto_out_2_ar_bits_addr),
    .auto_in_ar_bits_len   (_axi4xbar_auto_out_2_ar_bits_len),
    .auto_in_ar_bits_size  (_axi4xbar_auto_out_2_ar_bits_size),
    .auto_in_ar_bits_burst (_axi4xbar_auto_out_2_ar_bits_burst),
    .auto_in_ar_bits_lock  (_axi4xbar_auto_out_2_ar_bits_lock),
    .auto_in_ar_bits_cache (_axi4xbar_auto_out_2_ar_bits_cache),
    .auto_in_ar_bits_prot  (_axi4xbar_auto_out_2_ar_bits_prot),
    .auto_in_ar_bits_qos   (_axi4xbar_auto_out_2_ar_bits_qos),
    .auto_in_r_ready       (_axi4xbar_auto_out_2_r_ready),
    .auto_in_r_valid       (_sd_auto_in_r_valid),
    .auto_in_r_bits_id     (_sd_auto_in_r_bits_id),
    .auto_in_r_bits_data   (_sd_auto_in_r_bits_data),
    .auto_in_r_bits_resp   (_sd_auto_in_r_bits_resp),
    .auto_in_r_bits_last   (_sd_auto_in_r_bits_last)
  );
  AXI4IntrGenerator intrGen (
    .clock                 (clock),
    .reset                 (reset),
    .auto_in_aw_ready      (_intrGen_auto_in_aw_ready),
    .auto_in_aw_valid      (_axi4xbar_auto_out_3_aw_valid),
    .auto_in_aw_bits_id    (_axi4xbar_auto_out_3_aw_bits_id),
    .auto_in_aw_bits_addr  (_axi4xbar_auto_out_3_aw_bits_addr),
    .auto_in_aw_bits_len   (_axi4xbar_auto_out_3_aw_bits_len),
    .auto_in_aw_bits_size  (_axi4xbar_auto_out_3_aw_bits_size),
    .auto_in_aw_bits_burst (_axi4xbar_auto_out_3_aw_bits_burst),
    .auto_in_aw_bits_lock  (_axi4xbar_auto_out_3_aw_bits_lock),
    .auto_in_aw_bits_cache (_axi4xbar_auto_out_3_aw_bits_cache),
    .auto_in_aw_bits_prot  (_axi4xbar_auto_out_3_aw_bits_prot),
    .auto_in_aw_bits_qos   (_axi4xbar_auto_out_3_aw_bits_qos),
    .auto_in_w_ready       (_intrGen_auto_in_w_ready),
    .auto_in_w_valid       (_axi4xbar_auto_out_3_w_valid),
    .auto_in_w_bits_data   (_axi4xbar_auto_out_3_w_bits_data),
    .auto_in_w_bits_strb   (_axi4xbar_auto_out_3_w_bits_strb),
    .auto_in_w_bits_last   (_axi4xbar_auto_out_3_w_bits_last),
    .auto_in_b_ready       (_axi4xbar_auto_out_3_b_ready),
    .auto_in_b_valid       (_intrGen_auto_in_b_valid),
    .auto_in_b_bits_id     (_intrGen_auto_in_b_bits_id),
    .auto_in_b_bits_resp   (_intrGen_auto_in_b_bits_resp),
    .auto_in_ar_ready      (_intrGen_auto_in_ar_ready),
    .auto_in_ar_valid      (_axi4xbar_auto_out_3_ar_valid),
    .auto_in_ar_bits_id    (_axi4xbar_auto_out_3_ar_bits_id),
    .auto_in_ar_bits_addr  (_axi4xbar_auto_out_3_ar_bits_addr),
    .auto_in_ar_bits_len   (_axi4xbar_auto_out_3_ar_bits_len),
    .auto_in_ar_bits_size  (_axi4xbar_auto_out_3_ar_bits_size),
    .auto_in_ar_bits_burst (_axi4xbar_auto_out_3_ar_bits_burst),
    .auto_in_ar_bits_lock  (_axi4xbar_auto_out_3_ar_bits_lock),
    .auto_in_ar_bits_cache (_axi4xbar_auto_out_3_ar_bits_cache),
    .auto_in_ar_bits_prot  (_axi4xbar_auto_out_3_ar_bits_prot),
    .auto_in_ar_bits_qos   (_axi4xbar_auto_out_3_ar_bits_qos),
    .auto_in_r_ready       (_axi4xbar_auto_out_3_r_ready),
    .auto_in_r_valid       (_intrGen_auto_in_r_valid),
    .auto_in_r_bits_id     (_intrGen_auto_in_r_bits_id),
    .auto_in_r_bits_data   (_intrGen_auto_in_r_bits_data),
    .auto_in_r_bits_resp   (_intrGen_auto_in_r_bits_resp),
    .auto_in_r_bits_last   (_intrGen_auto_in_r_bits_last),
    .io_extra_intrVec      (io_interrupt_intrVec)
  );
  AXI4Error error (
    .clock                 (clock),
    .reset                 (reset),
    .auto_in_aw_ready      (_error_auto_in_aw_ready),
    .auto_in_aw_valid      (_axi4xbar_auto_out_4_aw_valid),
    .auto_in_aw_bits_id    (_axi4xbar_auto_out_4_aw_bits_id),
    .auto_in_aw_bits_addr  (_axi4xbar_auto_out_4_aw_bits_addr),
    .auto_in_aw_bits_len   (_axi4xbar_auto_out_4_aw_bits_len),
    .auto_in_aw_bits_size  (_axi4xbar_auto_out_4_aw_bits_size),
    .auto_in_aw_bits_burst (_axi4xbar_auto_out_4_aw_bits_burst),
    .auto_in_aw_bits_lock  (_axi4xbar_auto_out_4_aw_bits_lock),
    .auto_in_aw_bits_cache (_axi4xbar_auto_out_4_aw_bits_cache),
    .auto_in_aw_bits_prot  (_axi4xbar_auto_out_4_aw_bits_prot),
    .auto_in_aw_bits_qos   (_axi4xbar_auto_out_4_aw_bits_qos),
    .auto_in_w_ready       (_error_auto_in_w_ready),
    .auto_in_w_valid       (_axi4xbar_auto_out_4_w_valid),
    .auto_in_w_bits_data   (_axi4xbar_auto_out_4_w_bits_data),
    .auto_in_w_bits_strb   (_axi4xbar_auto_out_4_w_bits_strb),
    .auto_in_w_bits_last   (_axi4xbar_auto_out_4_w_bits_last),
    .auto_in_b_ready       (_axi4xbar_auto_out_4_b_ready),
    .auto_in_b_valid       (_error_auto_in_b_valid),
    .auto_in_b_bits_id     (_error_auto_in_b_bits_id),
    .auto_in_ar_ready      (_error_auto_in_ar_ready),
    .auto_in_ar_valid      (_axi4xbar_auto_out_4_ar_valid),
    .auto_in_ar_bits_id    (_axi4xbar_auto_out_4_ar_bits_id),
    .auto_in_ar_bits_addr  (_axi4xbar_auto_out_4_ar_bits_addr),
    .auto_in_ar_bits_len   (_axi4xbar_auto_out_4_ar_bits_len),
    .auto_in_ar_bits_size  (_axi4xbar_auto_out_4_ar_bits_size),
    .auto_in_ar_bits_burst (_axi4xbar_auto_out_4_ar_bits_burst),
    .auto_in_ar_bits_lock  (_axi4xbar_auto_out_4_ar_bits_lock),
    .auto_in_ar_bits_cache (_axi4xbar_auto_out_4_ar_bits_cache),
    .auto_in_ar_bits_prot  (_axi4xbar_auto_out_4_ar_bits_prot),
    .auto_in_ar_bits_qos   (_axi4xbar_auto_out_4_ar_bits_qos),
    .auto_in_r_ready       (_axi4xbar_auto_out_4_r_ready),
    .auto_in_r_valid       (_error_auto_in_r_valid),
    .auto_in_r_bits_id     (_error_auto_in_r_bits_id)
  );
  AXI4Xbar axi4xbar (
    .clock                    (clock),
    .reset                    (reset),
    .auto_in_aw_ready         (io_axi4_0_aw_ready),
    .auto_in_aw_valid         (io_axi4_0_aw_valid),
    .auto_in_aw_bits_id       (io_axi4_0_aw_bits_id),
    .auto_in_aw_bits_addr     (io_axi4_0_aw_bits_addr),
    .auto_in_aw_bits_len      (io_axi4_0_aw_bits_len),
    .auto_in_aw_bits_size     (io_axi4_0_aw_bits_size),
    .auto_in_aw_bits_burst    (io_axi4_0_aw_bits_burst),
    .auto_in_aw_bits_lock     (io_axi4_0_aw_bits_lock),
    .auto_in_aw_bits_cache    (io_axi4_0_aw_bits_cache),
    .auto_in_aw_bits_prot     (io_axi4_0_aw_bits_prot),
    .auto_in_aw_bits_qos      (io_axi4_0_aw_bits_qos),
    .auto_in_w_ready          (io_axi4_0_w_ready),
    .auto_in_w_valid          (io_axi4_0_w_valid),
    .auto_in_w_bits_data      (io_axi4_0_w_bits_data),
    .auto_in_w_bits_strb      (io_axi4_0_w_bits_strb),
    .auto_in_w_bits_last      (io_axi4_0_w_bits_last),
    .auto_in_b_ready          (io_axi4_0_b_ready),
    .auto_in_b_valid          (io_axi4_0_b_valid),
    .auto_in_b_bits_id        (io_axi4_0_b_bits_id),
    .auto_in_b_bits_resp      (io_axi4_0_b_bits_resp),
    .auto_in_ar_ready         (io_axi4_0_ar_ready),
    .auto_in_ar_valid         (io_axi4_0_ar_valid),
    .auto_in_ar_bits_id       (io_axi4_0_ar_bits_id),
    .auto_in_ar_bits_addr     (io_axi4_0_ar_bits_addr),
    .auto_in_ar_bits_len      (io_axi4_0_ar_bits_len),
    .auto_in_ar_bits_size     (io_axi4_0_ar_bits_size),
    .auto_in_ar_bits_burst    (io_axi4_0_ar_bits_burst),
    .auto_in_ar_bits_lock     (io_axi4_0_ar_bits_lock),
    .auto_in_ar_bits_cache    (io_axi4_0_ar_bits_cache),
    .auto_in_ar_bits_prot     (io_axi4_0_ar_bits_prot),
    .auto_in_ar_bits_qos      (io_axi4_0_ar_bits_qos),
    .auto_in_r_ready          (io_axi4_0_r_ready),
    .auto_in_r_valid          (io_axi4_0_r_valid),
    .auto_in_r_bits_id        (io_axi4_0_r_bits_id),
    .auto_in_r_bits_data      (io_axi4_0_r_bits_data),
    .auto_in_r_bits_resp      (io_axi4_0_r_bits_resp),
    .auto_in_r_bits_last      (io_axi4_0_r_bits_last),
    .auto_out_4_aw_ready      (_error_auto_in_aw_ready),
    .auto_out_4_aw_valid      (_axi4xbar_auto_out_4_aw_valid),
    .auto_out_4_aw_bits_id    (_axi4xbar_auto_out_4_aw_bits_id),
    .auto_out_4_aw_bits_addr  (_axi4xbar_auto_out_4_aw_bits_addr),
    .auto_out_4_aw_bits_len   (_axi4xbar_auto_out_4_aw_bits_len),
    .auto_out_4_aw_bits_size  (_axi4xbar_auto_out_4_aw_bits_size),
    .auto_out_4_aw_bits_burst (_axi4xbar_auto_out_4_aw_bits_burst),
    .auto_out_4_aw_bits_lock  (_axi4xbar_auto_out_4_aw_bits_lock),
    .auto_out_4_aw_bits_cache (_axi4xbar_auto_out_4_aw_bits_cache),
    .auto_out_4_aw_bits_prot  (_axi4xbar_auto_out_4_aw_bits_prot),
    .auto_out_4_aw_bits_qos   (_axi4xbar_auto_out_4_aw_bits_qos),
    .auto_out_4_w_ready       (_error_auto_in_w_ready),
    .auto_out_4_w_valid       (_axi4xbar_auto_out_4_w_valid),
    .auto_out_4_w_bits_data   (_axi4xbar_auto_out_4_w_bits_data),
    .auto_out_4_w_bits_strb   (_axi4xbar_auto_out_4_w_bits_strb),
    .auto_out_4_w_bits_last   (_axi4xbar_auto_out_4_w_bits_last),
    .auto_out_4_b_ready       (_axi4xbar_auto_out_4_b_ready),
    .auto_out_4_b_valid       (_error_auto_in_b_valid),
    .auto_out_4_b_bits_id     (_error_auto_in_b_bits_id),
    .auto_out_4_ar_ready      (_error_auto_in_ar_ready),
    .auto_out_4_ar_valid      (_axi4xbar_auto_out_4_ar_valid),
    .auto_out_4_ar_bits_id    (_axi4xbar_auto_out_4_ar_bits_id),
    .auto_out_4_ar_bits_addr  (_axi4xbar_auto_out_4_ar_bits_addr),
    .auto_out_4_ar_bits_len   (_axi4xbar_auto_out_4_ar_bits_len),
    .auto_out_4_ar_bits_size  (_axi4xbar_auto_out_4_ar_bits_size),
    .auto_out_4_ar_bits_burst (_axi4xbar_auto_out_4_ar_bits_burst),
    .auto_out_4_ar_bits_lock  (_axi4xbar_auto_out_4_ar_bits_lock),
    .auto_out_4_ar_bits_cache (_axi4xbar_auto_out_4_ar_bits_cache),
    .auto_out_4_ar_bits_prot  (_axi4xbar_auto_out_4_ar_bits_prot),
    .auto_out_4_ar_bits_qos   (_axi4xbar_auto_out_4_ar_bits_qos),
    .auto_out_4_r_ready       (_axi4xbar_auto_out_4_r_ready),
    .auto_out_4_r_valid       (_error_auto_in_r_valid),
    .auto_out_4_r_bits_id     (_error_auto_in_r_bits_id),
    .auto_out_3_aw_ready      (_intrGen_auto_in_aw_ready),
    .auto_out_3_aw_valid      (_axi4xbar_auto_out_3_aw_valid),
    .auto_out_3_aw_bits_id    (_axi4xbar_auto_out_3_aw_bits_id),
    .auto_out_3_aw_bits_addr  (_axi4xbar_auto_out_3_aw_bits_addr),
    .auto_out_3_aw_bits_len   (_axi4xbar_auto_out_3_aw_bits_len),
    .auto_out_3_aw_bits_size  (_axi4xbar_auto_out_3_aw_bits_size),
    .auto_out_3_aw_bits_burst (_axi4xbar_auto_out_3_aw_bits_burst),
    .auto_out_3_aw_bits_lock  (_axi4xbar_auto_out_3_aw_bits_lock),
    .auto_out_3_aw_bits_cache (_axi4xbar_auto_out_3_aw_bits_cache),
    .auto_out_3_aw_bits_prot  (_axi4xbar_auto_out_3_aw_bits_prot),
    .auto_out_3_aw_bits_qos   (_axi4xbar_auto_out_3_aw_bits_qos),
    .auto_out_3_w_ready       (_intrGen_auto_in_w_ready),
    .auto_out_3_w_valid       (_axi4xbar_auto_out_3_w_valid),
    .auto_out_3_w_bits_data   (_axi4xbar_auto_out_3_w_bits_data),
    .auto_out_3_w_bits_strb   (_axi4xbar_auto_out_3_w_bits_strb),
    .auto_out_3_w_bits_last   (_axi4xbar_auto_out_3_w_bits_last),
    .auto_out_3_b_ready       (_axi4xbar_auto_out_3_b_ready),
    .auto_out_3_b_valid       (_intrGen_auto_in_b_valid),
    .auto_out_3_b_bits_id     (_intrGen_auto_in_b_bits_id),
    .auto_out_3_b_bits_resp   (_intrGen_auto_in_b_bits_resp),
    .auto_out_3_ar_ready      (_intrGen_auto_in_ar_ready),
    .auto_out_3_ar_valid      (_axi4xbar_auto_out_3_ar_valid),
    .auto_out_3_ar_bits_id    (_axi4xbar_auto_out_3_ar_bits_id),
    .auto_out_3_ar_bits_addr  (_axi4xbar_auto_out_3_ar_bits_addr),
    .auto_out_3_ar_bits_len   (_axi4xbar_auto_out_3_ar_bits_len),
    .auto_out_3_ar_bits_size  (_axi4xbar_auto_out_3_ar_bits_size),
    .auto_out_3_ar_bits_burst (_axi4xbar_auto_out_3_ar_bits_burst),
    .auto_out_3_ar_bits_lock  (_axi4xbar_auto_out_3_ar_bits_lock),
    .auto_out_3_ar_bits_cache (_axi4xbar_auto_out_3_ar_bits_cache),
    .auto_out_3_ar_bits_prot  (_axi4xbar_auto_out_3_ar_bits_prot),
    .auto_out_3_ar_bits_qos   (_axi4xbar_auto_out_3_ar_bits_qos),
    .auto_out_3_r_ready       (_axi4xbar_auto_out_3_r_ready),
    .auto_out_3_r_valid       (_intrGen_auto_in_r_valid),
    .auto_out_3_r_bits_id     (_intrGen_auto_in_r_bits_id),
    .auto_out_3_r_bits_data   (_intrGen_auto_in_r_bits_data),
    .auto_out_3_r_bits_resp   (_intrGen_auto_in_r_bits_resp),
    .auto_out_3_r_bits_last   (_intrGen_auto_in_r_bits_last),
    .auto_out_2_aw_ready      (_sd_auto_in_aw_ready),
    .auto_out_2_aw_valid      (_axi4xbar_auto_out_2_aw_valid),
    .auto_out_2_aw_bits_id    (_axi4xbar_auto_out_2_aw_bits_id),
    .auto_out_2_aw_bits_addr  (_axi4xbar_auto_out_2_aw_bits_addr),
    .auto_out_2_aw_bits_len   (_axi4xbar_auto_out_2_aw_bits_len),
    .auto_out_2_aw_bits_size  (_axi4xbar_auto_out_2_aw_bits_size),
    .auto_out_2_aw_bits_burst (_axi4xbar_auto_out_2_aw_bits_burst),
    .auto_out_2_aw_bits_lock  (_axi4xbar_auto_out_2_aw_bits_lock),
    .auto_out_2_aw_bits_cache (_axi4xbar_auto_out_2_aw_bits_cache),
    .auto_out_2_aw_bits_prot  (_axi4xbar_auto_out_2_aw_bits_prot),
    .auto_out_2_aw_bits_qos   (_axi4xbar_auto_out_2_aw_bits_qos),
    .auto_out_2_w_ready       (_sd_auto_in_w_ready),
    .auto_out_2_w_valid       (_axi4xbar_auto_out_2_w_valid),
    .auto_out_2_w_bits_data   (_axi4xbar_auto_out_2_w_bits_data),
    .auto_out_2_w_bits_strb   (_axi4xbar_auto_out_2_w_bits_strb),
    .auto_out_2_w_bits_last   (_axi4xbar_auto_out_2_w_bits_last),
    .auto_out_2_b_ready       (_axi4xbar_auto_out_2_b_ready),
    .auto_out_2_b_valid       (_sd_auto_in_b_valid),
    .auto_out_2_b_bits_id     (_sd_auto_in_b_bits_id),
    .auto_out_2_b_bits_resp   (_sd_auto_in_b_bits_resp),
    .auto_out_2_ar_ready      (_sd_auto_in_ar_ready),
    .auto_out_2_ar_valid      (_axi4xbar_auto_out_2_ar_valid),
    .auto_out_2_ar_bits_id    (_axi4xbar_auto_out_2_ar_bits_id),
    .auto_out_2_ar_bits_addr  (_axi4xbar_auto_out_2_ar_bits_addr),
    .auto_out_2_ar_bits_len   (_axi4xbar_auto_out_2_ar_bits_len),
    .auto_out_2_ar_bits_size  (_axi4xbar_auto_out_2_ar_bits_size),
    .auto_out_2_ar_bits_burst (_axi4xbar_auto_out_2_ar_bits_burst),
    .auto_out_2_ar_bits_lock  (_axi4xbar_auto_out_2_ar_bits_lock),
    .auto_out_2_ar_bits_cache (_axi4xbar_auto_out_2_ar_bits_cache),
    .auto_out_2_ar_bits_prot  (_axi4xbar_auto_out_2_ar_bits_prot),
    .auto_out_2_ar_bits_qos   (_axi4xbar_auto_out_2_ar_bits_qos),
    .auto_out_2_r_ready       (_axi4xbar_auto_out_2_r_ready),
    .auto_out_2_r_valid       (_sd_auto_in_r_valid),
    .auto_out_2_r_bits_id     (_sd_auto_in_r_bits_id),
    .auto_out_2_r_bits_data   (_sd_auto_in_r_bits_data),
    .auto_out_2_r_bits_resp   (_sd_auto_in_r_bits_resp),
    .auto_out_2_r_bits_last   (_sd_auto_in_r_bits_last),
    .auto_out_1_aw_ready      (_flash_auto_in_aw_ready),
    .auto_out_1_aw_valid      (_axi4xbar_auto_out_1_aw_valid),
    .auto_out_1_aw_bits_id    (_axi4xbar_auto_out_1_aw_bits_id),
    .auto_out_1_aw_bits_addr  (_axi4xbar_auto_out_1_aw_bits_addr),
    .auto_out_1_aw_bits_len   (_axi4xbar_auto_out_1_aw_bits_len),
    .auto_out_1_aw_bits_size  (_axi4xbar_auto_out_1_aw_bits_size),
    .auto_out_1_aw_bits_burst (_axi4xbar_auto_out_1_aw_bits_burst),
    .auto_out_1_aw_bits_lock  (_axi4xbar_auto_out_1_aw_bits_lock),
    .auto_out_1_aw_bits_cache (_axi4xbar_auto_out_1_aw_bits_cache),
    .auto_out_1_aw_bits_prot  (_axi4xbar_auto_out_1_aw_bits_prot),
    .auto_out_1_aw_bits_qos   (_axi4xbar_auto_out_1_aw_bits_qos),
    .auto_out_1_w_ready       (_flash_auto_in_w_ready),
    .auto_out_1_w_valid       (_axi4xbar_auto_out_1_w_valid),
    .auto_out_1_w_bits_data   (_axi4xbar_auto_out_1_w_bits_data),
    .auto_out_1_w_bits_strb   (_axi4xbar_auto_out_1_w_bits_strb),
    .auto_out_1_w_bits_last   (_axi4xbar_auto_out_1_w_bits_last),
    .auto_out_1_b_ready       (_axi4xbar_auto_out_1_b_ready),
    .auto_out_1_b_valid       (_flash_auto_in_b_valid),
    .auto_out_1_b_bits_id     (_flash_auto_in_b_bits_id),
    .auto_out_1_b_bits_resp   (_flash_auto_in_b_bits_resp),
    .auto_out_1_ar_ready      (_flash_auto_in_ar_ready),
    .auto_out_1_ar_valid      (_axi4xbar_auto_out_1_ar_valid),
    .auto_out_1_ar_bits_id    (_axi4xbar_auto_out_1_ar_bits_id),
    .auto_out_1_ar_bits_addr  (_axi4xbar_auto_out_1_ar_bits_addr),
    .auto_out_1_ar_bits_len   (_axi4xbar_auto_out_1_ar_bits_len),
    .auto_out_1_ar_bits_size  (_axi4xbar_auto_out_1_ar_bits_size),
    .auto_out_1_ar_bits_burst (_axi4xbar_auto_out_1_ar_bits_burst),
    .auto_out_1_ar_bits_lock  (_axi4xbar_auto_out_1_ar_bits_lock),
    .auto_out_1_ar_bits_cache (_axi4xbar_auto_out_1_ar_bits_cache),
    .auto_out_1_ar_bits_prot  (_axi4xbar_auto_out_1_ar_bits_prot),
    .auto_out_1_ar_bits_qos   (_axi4xbar_auto_out_1_ar_bits_qos),
    .auto_out_1_r_ready       (_axi4xbar_auto_out_1_r_ready),
    .auto_out_1_r_valid       (_flash_auto_in_r_valid),
    .auto_out_1_r_bits_id     (_flash_auto_in_r_bits_id),
    .auto_out_1_r_bits_data   (_flash_auto_in_r_bits_data),
    .auto_out_1_r_bits_resp   (_flash_auto_in_r_bits_resp),
    .auto_out_1_r_bits_last   (_flash_auto_in_r_bits_last),
    .auto_out_0_aw_ready      (_uart_auto_in_aw_ready),
    .auto_out_0_aw_valid      (_axi4xbar_auto_out_0_aw_valid),
    .auto_out_0_aw_bits_id    (_axi4xbar_auto_out_0_aw_bits_id),
    .auto_out_0_aw_bits_addr  (_axi4xbar_auto_out_0_aw_bits_addr),
    .auto_out_0_aw_bits_len   (_axi4xbar_auto_out_0_aw_bits_len),
    .auto_out_0_aw_bits_size  (_axi4xbar_auto_out_0_aw_bits_size),
    .auto_out_0_aw_bits_burst (_axi4xbar_auto_out_0_aw_bits_burst),
    .auto_out_0_aw_bits_lock  (_axi4xbar_auto_out_0_aw_bits_lock),
    .auto_out_0_aw_bits_cache (_axi4xbar_auto_out_0_aw_bits_cache),
    .auto_out_0_aw_bits_prot  (_axi4xbar_auto_out_0_aw_bits_prot),
    .auto_out_0_aw_bits_qos   (_axi4xbar_auto_out_0_aw_bits_qos),
    .auto_out_0_w_ready       (_uart_auto_in_w_ready),
    .auto_out_0_w_valid       (_axi4xbar_auto_out_0_w_valid),
    .auto_out_0_w_bits_data   (_axi4xbar_auto_out_0_w_bits_data),
    .auto_out_0_w_bits_strb   (_axi4xbar_auto_out_0_w_bits_strb),
    .auto_out_0_w_bits_last   (_axi4xbar_auto_out_0_w_bits_last),
    .auto_out_0_b_ready       (_axi4xbar_auto_out_0_b_ready),
    .auto_out_0_b_valid       (_uart_auto_in_b_valid),
    .auto_out_0_b_bits_id     (_uart_auto_in_b_bits_id),
    .auto_out_0_b_bits_resp   (_uart_auto_in_b_bits_resp),
    .auto_out_0_ar_ready      (_uart_auto_in_ar_ready),
    .auto_out_0_ar_valid      (_axi4xbar_auto_out_0_ar_valid),
    .auto_out_0_ar_bits_id    (_axi4xbar_auto_out_0_ar_bits_id),
    .auto_out_0_ar_bits_addr  (_axi4xbar_auto_out_0_ar_bits_addr),
    .auto_out_0_ar_bits_len   (_axi4xbar_auto_out_0_ar_bits_len),
    .auto_out_0_ar_bits_size  (_axi4xbar_auto_out_0_ar_bits_size),
    .auto_out_0_ar_bits_burst (_axi4xbar_auto_out_0_ar_bits_burst),
    .auto_out_0_ar_bits_lock  (_axi4xbar_auto_out_0_ar_bits_lock),
    .auto_out_0_ar_bits_cache (_axi4xbar_auto_out_0_ar_bits_cache),
    .auto_out_0_ar_bits_prot  (_axi4xbar_auto_out_0_ar_bits_prot),
    .auto_out_0_ar_bits_qos   (_axi4xbar_auto_out_0_ar_bits_qos),
    .auto_out_0_r_ready       (_axi4xbar_auto_out_0_r_ready),
    .auto_out_0_r_valid       (_uart_auto_in_r_valid),
    .auto_out_0_r_bits_id     (_uart_auto_in_r_bits_id),
    .auto_out_0_r_bits_data   (_uart_auto_in_r_bits_data),
    .auto_out_0_r_bits_resp   (_uart_auto_in_r_bits_resp),
    .auto_out_0_r_bits_last   (_uart_auto_in_r_bits_last)
  );
endmodule

