// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module SRAMTemplate_63(
  input         clock,
  input         reset,
  output        io_r_req_ready,
  input         io_r_req_valid,
  input  [6:0]  io_r_req_bits_setIdx,
  output [35:0] io_r_resp_data_0,
  input         io_w_req_valid,
  input  [6:0]  io_w_req_bits_setIdx,
  input  [35:0] io_w_req_bits_data_0,
  input  [35:0] io_w_req_bits_flattened_bitmask
);

  wire        io_r_req_ready_0;
  wire [35:0] _array_RW0_rdata;
  wire        _rcg_out_clock;
  reg         _resetState;
  reg  [6:0]  _resetSet;
  wire        ren = io_r_req_ready_0 & io_r_req_valid;
  wire        wen = io_w_req_valid | _resetState;
  reg         rdata_last_REG;
  reg  [35:0] rdata_hold_data_0;
  assign io_r_req_ready_0 = ~_resetState & ~io_w_req_valid;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
    _resetState <= 1'h0;
      _resetSet <= 7'h0;
      rdata_last_REG <= 1'h0;
    end
    else begin
      _resetState <= ~(_resetState & (&_resetSet)) & _resetState;
      if (_resetState)
        _resetSet <= 7'(_resetSet + 7'h1);
      rdata_last_REG <= ren;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (rdata_last_REG)
      rdata_hold_data_0 <= _array_RW0_rdata;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:5];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h6; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        _resetState = _RANDOM[3'h0][0];
        _resetSet = _RANDOM[3'h0][7:1];
        rdata_last_REG = _RANDOM[3'h3][29];
        rdata_hold_data_0 = {_RANDOM[3'h3][31:30], _RANDOM[3'h4], _RANDOM[3'h5][1:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        _resetState = 1'h1;
        _resetSet = 7'h0;
        rdata_last_REG = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MbistClockGateCell rcg (
    .clock     (clock),
    .E         (ren | wen),
    .out_clock (_rcg_out_clock)
  );
  sram_array_1p128x36m1s1h0l1_bp_ittage array (
    .RW0_clk   (_rcg_out_clock),
    .RW0_addr
      (wen ? (_resetState ? _resetSet : io_w_req_bits_setIdx) : io_r_req_bits_setIdx),
    .RW0_en    (wen | ren),
    .RW0_wmode (wen),
    .RW0_wmask (_resetState ? 36'hFFFFFFFFF : io_w_req_bits_flattened_bitmask),
    .RW0_wdata (_resetState ? 36'h0 : io_w_req_bits_data_0),
    .RW0_rdata (_array_RW0_rdata)
  );
  assign io_r_req_ready = io_r_req_ready_0;
  assign io_r_resp_data_0 = rdata_last_REG ? _array_RW0_rdata : rdata_hold_data_0;
endmodule

